"""The 256 colours a DXF's colour numbers stand for, as the original sees them.

A DXF says what colour a line is with a number from 1 to 255 (group code 62),
and every program has its own idea of what those numbers look like.  The
original's table is not in the file -- it is built in memory when the program
starts -- so this asks it instead: a DXF of 255 lines, one per colour, is
opened by the original and saved as .jww, and what it made of each line says
what RGB it believes that colour to be.

    python tools/mkaci.py --dxf tmp/aci1.dxf 1 128      # make the question
    python tools/mkaci.py                               # read the answers

The answers are decomp/res/aci1.jww and aci2.jww (tools/refanswers.sh makes
them); the result is src/gen/aci.h.

How a line's colour comes back says which of two things happened, and either
one tells us the RGB (FUN_0049da00):

  * the colour was already one of the drawing's eight printing pens, and the
    line carries that pen's number -- so the RGB is that pen's;
  * or it was already one of its 任意色, and the entry holds the RGB as it
    is, because that is what an exact match means;
  * or the original made a new entry, and *that* entry holds the RGB with
    its first and last bytes swapped -- which is why looking the same colour
    up twice makes two entries rather than one, and why a colour that is the
    swap of an earlier one lands on the earlier one's entry.

Which of the last two happened is told by the number: entries are handed out
in order, so an entry past the highest one seen so far is a new one.
"""
import io
import sys

sys.path.insert(0, 'tools')
import jww

PROLOGUE = 'decomp/res/pens.dxf'
LAYER = '_0-0__基準'.encode('cp932')


def make_dxf(path, lo, hi):
    """A DXF of one line per colour, on the prologue the original writes."""
    src = io.open(PROLOGUE, 'rb').read()
    head = src[:src.index(b'ENTITIES\r\n') + len(b'ENTITIES\r\n')]

    def g(code, val):
        return ('%3d\r\n%s\r\n' % (code, val)).encode('cp932')

    out, y = [head], 61400
    for c in range(lo, hi + 1):
        out.append(g(0, 'LINE'))
        out.append(b'  8\r\n' + LAYER + b'\r\n')
        out.append(g(6, 'CONTINUOUS'))
        out.append(('%3d\r\n%5d\r\n' % (62, c)).encode())
        out.append(g(10, '64100') + g(20, y) + g(11, '104100') + g(21, y))
        y += 100
    out.append(g(0, 'ENDSEC') + g(0, 'EOF'))
    io.open(path, 'wb').write(b''.join(out))


def read(path):
    ar = jww.Ar(io.open(path, 'rb').read())
    v, name, groups = jww.read_header(ar, note=lambda s: None)
    objs = jww.read_objects(ar, v, note=lambda s: None)
    lines = [o for o in objs if o['class'] == 'CDataSen']
    return lines, dict(jww.TABLES)


def swap(v):
    return ((v & 0xff) << 16) | (v & 0xff00) | (v >> 16 & 0xff)


def main():
    if sys.argv[1:2] == ['--dxf']:
        make_dxf(sys.argv[2], int(sys.argv[3]), int(sys.argv[4]))
        return
    pal = [0] * 256
    for path, lo in (('decomp/res/aci1.jww', 1), ('decomp/res/aci2.jww', 129)):
        lines, tab = read(path)
        colour = [c for c, w in tab['color']]
        pen = [c for c, flag, w in tab['ppen']]
        top = 116               # the last 任意色 a fresh drawing has
        for i, o in enumerate(lines):
            code = o['type']
            if code < 100:
                pal[lo + i] = pen[code]
            elif code > top:
                pal[lo + i] = swap(colour[code - 100])
                top = code
            else:
                pal[lo + i] = colour[code - 100]
    out = ["/* Generated by tools/mkaci.py -- do not edit.",
           " *",
           " * What the original makes of a DXF's colour numbers: entry n is",
           " * the COLORREF (0x00bbggrr) it believes colour n to be.  Entry 0",
           " * is never used -- 0 is BYBLOCK.",
           " */",
           "#ifndef JW_GEN_ACI_H",
           "#define JW_GEN_ACI_H",
           "",
           "static const unsigned int JW_ACI[256] = {"]
    for i in range(0, 256, 6):
        out.append('    ' + ' '.join('0x%06x,' % v for v in pal[i:i + 6]))
    out.append("};")
    out.append("")
    out.append("#endif")
    io.open('src/gen/aci.h', 'w', encoding='utf-8', newline='\n') \
        .write('\n'.join(out) + '\n')
    print('src/gen/aci.h: 256 colours')


if __name__ == '__main__':
    main()
