#!/usr/bin/env python3
"""Generate src/gen/accel.h -- the frame's keyboard shortcuts.

The menu names its shortcuts (Ctrl+N and the rest) because the original's menu
resource spells them out, but naming one does not make it work: the keys come
from a separate ACCELERATOR resource that the frame passes every message
through.  This turns that resource into a table the native build can hand to
CreateAcceleratorTable, so a shortcut arrives at app_command() as the same
WM_COMMAND a menu item sends.

    python tools/mkaccel.py            # <- decomp/res/accel.txt, by tools/rsrc.py

Only table 320 is taken: it is the frame's.  30997 is the print preview's
(PageUp, PageDown, Escape), which this port has no preview to use it with.
"""
import os
import re

SRC = 'decomp/res/accel.txt'
OUT = 'src/gen/accel.h'
WANT = 320

FVIRTKEY, FSHIFT, FCONTROL, FALT = 0x01, 0x04, 0x08, 0x10

# What the keys are called, for the comments -- enough of VK_ to name the ones
# this table uses.
VK = {0x08: 'BACK', 0x1b: 'ESCAPE', 0x21: 'PRIOR', 0x22: 'NEXT',
      0x2d: 'INSERT', 0x2e: 'DELETE', 0x70: 'F1', 0x75: 'F6'}


def name(key):
    if key in VK:
        return 'VK_' + VK[key]
    if 0x30 <= key <= 0x5a:
        return chr(key)
    return '0x%04x' % key


def read():
    rows, on = [], False
    for line in open(SRC, encoding='utf-8'):
        line = line.strip()
        m = re.match(r'=== ACCELERATOR (\d+)$', line)
        if m:
            on = int(m.group(1)) == WANT
            continue
        if not on:
            continue
        m = re.match(r'key=0x([0-9a-f]+)\s*([CSA]*)\s+cmd=(\d+)', line)
        if not m:
            continue
        key = int(m.group(1), 16)
        mods = m.group(2)
        f = FVIRTKEY
        if 'C' in mods:
            f |= FCONTROL
        if 'S' in mods:
            f |= FSHIFT
        if 'A' in mods:
            f |= FALT
        rows.append((f, key, int(m.group(3)), mods))
    return rows


def main():
    rows = read()
    os.makedirs('src/gen', exist_ok=True)
    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* generated by tools/mkaccel.py from decomp/res/accel.txt --\n'
                '   the original\'s own ACCELERATOR %d */\n' % WANT)
        f.write('#ifndef JW_GEN_ACCEL_H\n#define JW_GEN_ACCEL_H\n\n')
        f.write('/* fVirt, key, cmd -- straight into an ACCEL[] */\n')
        f.write('static const struct { unsigned char virt;\n'
                '                      unsigned short key, cmd; } jw_accel[] = {\n')
        for virt, key, cmd, mods in rows:
            what = '+'.join([{'C': 'Ctrl', 'S': 'Shift', 'A': 'Alt'}[c]
                             for c in mods] + [name(key)])
            f.write('    { 0x%02x, 0x%04x, %5d },   /* %s */\n'
                    % (virt, key, cmd, what))
        f.write('};\n#define JW_NACCEL %d\n\n#endif\n' % len(rows))
    print('%s: %d shortcuts' % (OUT, len(rows)))


main()
