#!/usr/bin/env python3
"""Generate src/gen/bars.h -- the command bar for each command.

The command bar across the top is a CDialogBar, so what is on it are
ordinary Windows controls, and their positions are whatever Windows worked
out from the dialog template and the dialog font.  Rather than guess at that
conversion, tmp/bars.ps1 asks the running original: it starts Jw_cad, sends
each command in turn, and walks the frame's child windows with
EnumChildWindows, writing down each control's class, id, style, text and
rectangle in the frame's own client coordinates.  Nothing is drawn or
captured -- the window is shown but never read back.

What comes out (decomp/res/bars.txt) is exact.  It reproduces every position
that had been measured off the reference screen by hand: the 矩形 checkbox at
x=18 y=11, the two comboboxes at 185 and 319, the 端部点 button at 517 y=5
h=24, and the rest.
"""
import os
import re

# decomp/res/bars.txt is every command's bar as it is entered; bars2.txt is
# the one a few of them put up once a range is settled, which tools/bars.ps1
# cannot reach.  Those come in headed `=== command 1<cmd>` -- the command
# with a 1 in front -- and go into the same table, so the port looks the
# second stage up by 100000 + the command.
SRC = ['decomp/res/bars.txt', 'decomp/res/bars2.txt']
OUT = 'src/gen/bars.h'

# the windows that make up the frame itself, not the bar
SKIP = ('AfxFrameOrView', 'AfxControlBar', 'ToolbarWindow32', '#32770',
        'Edit')            # the edit inside a combobox, drawn with it

KIND = {'check': 0, 'button': 1, 'static': 2, 'combo': 3}


def esc(s):
    BS = chr(92)
    keep = '"' + BS + '?'
    out = []
    b = s.encode('cp932')
    for i, c in enumerate(b):
        if c > 0x7e or c < 0x20 or chr(c) in keep:
            out.append(BS + 'x%02x' % c)
            if i + 1 < len(b) and chr(b[i + 1]) in '0123456789abcdefABCDEF':
                out.append('" "')
        else:
            out.append(chr(c))
    return ''.join(out)


def kind_of(cls, style):
    if cls == 'ComboBox':
        return 'combo'
    if cls == 'Static':
        return 'static'
    if cls == 'Button':
        low = style & 0x0f
        if low == 3:            # BS_AUTOCHECKBOX
            return 'check'
        return 'button'         # BS_PUSHBUTTON, BS_DEFPUSHBUTTON, owner-draw
    return None


def read():
    bars, cur = [], None
    lines = []
    for p in SRC:
        if os.path.exists(p):
            lines += list(open(p, encoding='utf-8'))
    for line in lines:
        line = line.rstrip('\n')
        m = re.match(r'=== command (\d+)$', line)
        if m:
            cur = (int(m.group(1)), [])
            bars.append(cur)
            continue
        if cur is None or '|' not in line:
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if any(cls.startswith(s) for s in SKIP):
            continue
        k = kind_of(cls, int(style, 16))
        if k is None:
            continue
        cur[1].append((k, int(x), int(y), int(w), int(h),
                       (int(style, 16) & 0x0f) if cls == 'Static' else 0,
                       int(chk), int(en), int(cid), text))
    return bars


def main():
    bars = read()
    os.makedirs('src/gen', exist_ok=True)
    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* generated by tools/mkbars.py from decomp/res/bars.txt --\n'
                '   read out of the running original, see that script */\n')
        f.write('#ifndef JW_GEN_BARS_H\n#define JW_GEN_BARS_H\n\n')
        f.write('enum { JW_CTL_CHECK, JW_CTL_BUTTON, JW_CTL_STATIC,\n'
                '       JW_CTL_COMBO };\n\n')
        f.write('typedef struct {\n'
                '    short x, y, w, h;\n'
                '    unsigned short id;     /* the control id the original\n'
                '                              gives it -- what a press is\n'
                '                              dispatched on */\n'
                '    unsigned char kind;\n'
                '    unsigned char align;   /* a static\'s SS_ bits */\n'
                '    unsigned char checked; /* how the original has it when\n'
                '                              the command is entered */\n'
                '    unsigned char enabled;\n'
                '    const char *text;      /* CP932 */\n'
                '} jw_ctl_t;\n\n')
        for cmd, ctls in bars:
            f.write('static const jw_ctl_t jw_bar_%d[] = {\n' % cmd)
            for k, x, y, w, h, al, chk, en, cid, text in ctls:
                f.write('    { %4d, %3d, %4d, %3d, %5d, JW_CTL_%-6s,'
                        ' %d, %d, %d, "%s" },\n'
                        % (x, y, w, h, cid, KIND_NAME[k], al, chk, en,
                           esc(text)))
            f.write('};\n\n')
        f.write('typedef struct {\n'
                '    unsigned int cmd;      /* 100000 + it for the bar the\n'
                '                              command puts up once a range\n'
                '                              is settled */\n'
                '    unsigned short n;\n'
                '    const jw_ctl_t *c;\n'
                '} jw_bar_t;\n\n')
        f.write('static const jw_bar_t jw_bars[] = {\n')
        for cmd, ctls in bars:
            f.write('    { %6d, %2d, jw_bar_%d },\n' % (cmd, len(ctls), cmd))
        f.write('};\n#define JW_NBARS %d\n\n' % len(bars))
        f.write('#endif\n')
    print('%s: %d bars, %d controls'
          % (OUT, len(bars), sum(len(c) for _, c in bars)))


KIND_NAME = {'check': 'CHECK', 'button': 'BUTTON', 'static': 'STATIC',
             'combo': 'COMBO'}

if __name__ == '__main__':
    main()
