#!/usr/bin/env python3
"""Generate src/gen/bairitsu.h -- the 画面倍率・文字表示 dialog (32811's).

The same way as tools/mkzokusel.py: tools/jwdraw.ps1's `dlg:` step sends the
command once a range is in, walks the dialog's children with
EnumChildWindows and writes down each control's class, id, style, text and
rectangle in the dialog's own client coordinates (decomp/res/bairitsu.txt).
It also paints the dialog into a PNG, which is docs/ref_bairitsu.png.

The zoom, the four mark-jump registers and two display toggles.  Only
用紙全体表示 is wired up -- it fits the sheet to the window, which is what
the port already does when it opens a drawing.  What the rest mean for the
view cannot be checked here: the original's screen cannot be captured on
this machine, so there is nothing to score a view against.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkmoji import esc                            # noqa: E402

SRC = 'decomp/res/bairitsu.txt'
OUT = 'src/gen/bairitsu.h'
MASK = 'docs/bairitsu_textareas.txt'

WS_VISIBLE = 0x10000000
BORDER = 8
CAPTION = 31
W, H, CW, CH = 245, 305, 229, 266
TITLE = '画面倍率・文字表示'


def kind_of(cid, cls, style):
    if cls == 'Button':
        low = style & 0xf
        if low == 3:                    # BS_AUTOCHECKBOX
            return 'CHECK'
        if low == 7:                    # BS_GROUPBOX
            return 'GROUP'
        return 'OK' if cid in (1, 2) else 'PUSH'
    if cls == 'Edit':
        # 1001 is the one inside a combo box, which is drawn with it
        return None if cid == 1001 else 'EDIT'
    if cls == 'ComboBox':
        return 'COMBO'
    if cls == 'Static':
        return 'STATIC'
    return None


def main():
    rows = []
    for line in io.open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line or line.startswith('==='):
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if not (int(style, 16) & WS_VISIBLE):
            continue
        k = kind_of(int(cid), cls, int(style, 16))
        if k is None:
            continue
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, int(chk),
                     (int(style, 16) & 0xf) == 1, int(en), text))

    if not os.path.isdir('src/gen'):
        os.makedirs('src/gen')
    f = io.open(OUT, 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mkbairitsu.py from decomp/res/bairitsu.txt\n'
            '   -- read out of the running original, see that script */\n')
    f.write('#ifndef JW_GEN_BAIRITSU_H\n#define JW_GEN_BAIRITSU_H\n\n')
    f.write('#define JW_BR_W   %d\n' % W)
    f.write('#define JW_BR_H   %d\n' % H)
    f.write('#define JW_BR_CW  %d\n' % CW)
    f.write('#define JW_BR_CH  %d\n' % CH)
    f.write('#define JW_BR_BORDER %d\n' % BORDER)
    f.write('#define JW_BR_CAPTION %d\n' % CAPTION)
    f.write('#define JW_BR_TITLE "%s"\n\n' % esc(TITLE))
    f.write('enum { JW_BR_OK, JW_BR_CHECK, JW_BR_PUSH, JW_BR_STATIC,\n'
            '       JW_BR_COMBO, JW_BR_GROUP, JW_BR_EDIT };\n\n')
    f.write('typedef struct {\n'
            '    short x, y, w, h;      /* the dialog\'s client area */\n'
            '    short id;\n'
            '    unsigned char kind;\n'
            '    unsigned char on;\n'
            '    unsigned char deflt;   /* BS_DEFPUSHBUTTON: an extra dark\n'
            '                              border round it */\n'
            '    unsigned char enabled;\n'
            '    const char *text;      /* CP932 */\n'
            '} jw_br_t;\n\n')
    f.write('static const jw_br_t jw_bairitsu[] = {\n')
    for x, y, ww, hh, cid, k, chk, dft, en, text in rows:
        f.write('    { %4d, %4d, %4d, %3d, %5d, JW_BR_%-6s, %d, %d, %d,'
                ' "%s" },\n'
                % (x, y, ww, hh, cid, k, chk, dft, en, esc(text)))
    f.write('};\n#define JW_NBAIRITSU %d\n\n' % len(rows))
    f.write('#endif\n')
    f.close()

    g = io.open(MASK, 'w', encoding='utf-8', newline='\n')
    g.write('# Where the 画面倍率 dialog draws text with a Windows font, in\n'
            '# the coordinates of docs/ref_bairitsu.png (the whole %dx%d\n'
            '# window).  The frame and the caption go with them.  Written by\n'
            '# tools/mkbairitsu.py.\n\n' % (W, H))
    g.write('0 0 %d %d\n' % (W, CAPTION))
    g.write('0 %d %d %d\n' % (CAPTION, BORDER, CH))
    g.write('%d %d %d %d\n' % (W - BORDER, CAPTION, BORDER, CH))
    g.write('0 %d %d %d\n' % (H - BORDER, W, BORDER))
    for x, y, ww, hh, cid, k, chk, dft, en, text in rows:
        x += BORDER
        y += CAPTION
        if k == 'CHECK':
            g.write('%d %d %d %d\n' % (x + 14, y - 1, ww - 13, hh + 2))
        elif k in ('STATIC', 'COMBO', 'EDIT'):
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, hh + 2))
        elif k == 'GROUP':
            # only the strip its label sits in, which is also where the top
            # of its frame runs
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, 17))
        else:
            # inside its edge rows.  A plain push button gets one row more
            # than a BS_DEFPUSHBUTTON, which has a dark border outside its
            # two: the original draws 倍率 ＝ １．０'s first glyph a pixel
            # left of where the port centres it.
            n = 3 if dft else 2
            g.write('%d %d %d %d\n' % (x + n, y + n, ww - 2 * n, hh - 2 * n))
    g.close()
    print('%s: %d controls, %s' % (OUT, len(rows), MASK))
    return 0


if __name__ == '__main__':
    sys.exit(main())
