#!/usr/bin/env python3
"""Generate src/gen/blkedit.h -- the ブロック編集 dialog (32986's).

The same way as tools/mkzokusel.py: tools/jwdraw.ps1's `dlg:` step sends the
command once a range is in, walks the dialog's children with
EnumChildWindows and writes down each control's class, id, style, text and
rectangle in the dialog's own client coordinates (decomp/res/blkedit.txt).
It also paints the dialog into a PNG, which is docs/ref_blkedit.png.

The block's name, a button to change it, the two 編集結果を choices and
the usual pair.  The name box comes up holding the block's own name.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkmoji import esc                            # noqa: E402

SRC = 'decomp/res/blkedit.txt'
OUT = 'src/gen/blkedit.h'
MASK = 'docs/blkedit_textareas.txt'

WS_VISIBLE = 0x10000000
BORDER = 8
CAPTION = 31
W, H, CW, CH = 368, 147, 352, 108
TITLE = '選択されたブロックを編集します'


def kind_of(cid, cls, style):
    if cls == 'Button':
        if (style & 0xf) == 3:          # BS_AUTOCHECKBOX
            return 'CHECK'
        return 'OK' if cid in (1, 2) else 'PUSH'
    if cls == 'Edit':
        return 'EDIT'
    if cls == 'Static':
        return 'STATIC'
    return None


def main():
    rows = []
    for line in io.open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line or line.startswith('==='):
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if not (int(style, 16) & WS_VISIBLE):
            continue
        k = kind_of(int(cid), cls, int(style, 16))
        if k is None:
            continue
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, int(chk),
                     text))

    if not os.path.isdir('src/gen'):
        os.makedirs('src/gen')
    f = io.open(OUT, 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mkblkedit.py from decomp/res/blkedit.txt\n'
            '   -- read out of the running original, see that script */\n')
    f.write('#ifndef JW_GEN_BLKEDIT_H\n#define JW_GEN_BLKEDIT_H\n\n')
    f.write('#define JW_BE_W   %d\n' % W)
    f.write('#define JW_BE_H   %d\n' % H)
    f.write('#define JW_BE_CW  %d\n' % CW)
    f.write('#define JW_BE_CH  %d\n' % CH)
    f.write('#define JW_BE_BORDER %d\n' % BORDER)
    f.write('#define JW_BE_CAPTION %d\n' % CAPTION)
    f.write('#define JW_BE_TITLE "%s"\n\n' % esc(TITLE))
    f.write('enum { JW_BE_OK, JW_BE_CHECK, JW_BE_PUSH, JW_BE_STATIC,\n'
            '       JW_BE_EDIT };\n\n')
    f.write('typedef struct {\n'
            '    short x, y, w, h;      /* the dialog\'s client area */\n'
            '    short id;\n'
            '    unsigned char kind;\n'
            '    unsigned char on;\n'
            '    const char *text;      /* CP932 */\n'
            '} jw_be_t;\n\n')
    f.write('static const jw_be_t jw_blkedit[] = {\n')
    for x, y, ww, hh, cid, k, chk, text in rows:
        f.write('    { %4d, %4d, %4d, %3d, %5d, JW_BE_%-6s, %d, "%s" },\n'
                % (x, y, ww, hh, cid, k, chk, esc(text)))
    f.write('};\n#define JW_NBLKEDIT %d\n\n' % len(rows))
    f.write('#endif\n')
    f.close()

    g = io.open(MASK, 'w', encoding='utf-8', newline='\n')
    g.write('# Where the ブロック編集 dialog draws text with a Windows font, in\n'
            '# the coordinates of docs/ref_blkedit.png (the whole %dx%d\n'
            '# window).  The frame and the caption go with them.  Written by\n'
            '# tools/mkblkedit.py.\n\n' % (W, H))
    g.write('0 0 %d %d\n' % (W, CAPTION))
    g.write('0 %d %d %d\n' % (CAPTION, BORDER, CH))
    g.write('%d %d %d %d\n' % (W - BORDER, CAPTION, BORDER, CH))
    g.write('0 %d %d %d\n' % (H - BORDER, W, BORDER))
    for x, y, ww, hh, cid, k, chk, text in rows:
        x += BORDER
        y += CAPTION
        if k == 'CHECK':
            g.write('%d %d %d %d\n' % (x + 14, y - 1, ww - 13, hh + 2))
        elif k in ('STATIC', 'EDIT'):
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, hh + 2))
        else:
            g.write('%d %d %d %d\n' % (x + 3, y + 3, ww - 6, hh - 6))
    g.close()
    print('%s: %d controls, %s' % (OUT, len(rows), MASK))
    return 0


if __name__ == '__main__':
    sys.exit(main())
