#!/usr/bin/env python3
"""Generate src/gen/circle.h from decomp/res/circles.txt.

That file is what GDI itself draws, written down by tools/gdicirc.c: for each
radius, one quadrant of the circle as a walk from (0,r) to (r,0), two bits a
step.  src/draw.c mirrors the quadrant the other three ways.

Why a table at all: GDI's circle is not the textbook midpoint one.  For
radius 5 the textbook walk goes (0,5) (1,5) (2,5) (3,4) and GDI's goes
(0,5) (1,5) (2,4) (3,4), and no constant fudge of r squared reproduces it --
for radii 16, 18, 19, 50, 80 and 120 no such constant exists at all.  So the
only way to draw what GDI draws is to have asked it.
"""
import os

SRC = 'decomp/res/circles.txt'
OUT = 'src/gen/circle.h'
RMAX = 256


def read():
    walk = {}
    for line in open(SRC):
        if line.startswith('#'):
            continue
        odd, r, hexs = line.split()
        if hexs == '-':
            continue
        odd, r = int(odd), int(r)
        b = bytes.fromhex(hexs)
        steps = []
        qx, qy = 0, r
        for i in range(len(b) * 4):
            c = (b[i >> 2] >> ((i & 3) * 2)) & 3
            if qx >= r and qy <= 0:
                break
            steps.append(c)
            if c == 0:
                qx += 1
            elif c == 1:
                qy -= 1
            else:
                qx += 1
                qy -= 1
        assert (qx, qy) == (r, 0), (odd, r, qx, qy)
        walk[(odd, r)] = steps
    return walk


def main():
    walk = read()
    os.makedirs('src/gen', exist_ok=True)
    bits = [[], []]
    off = [[0] * (RMAX + 1) for _ in range(2)]
    ln = [[0] * (RMAX + 1) for _ in range(2)]
    for odd in (0, 1):
        for r in range(1, RMAX + 1):
            s = walk.get((odd, r))
            off[odd][r] = len(bits[odd])
            ln[odd][r] = len(s) if s else 0
            if s:
                bits[odd].extend(s)
    packed = []
    for odd in (0, 1):
        b = bytearray((len(bits[odd]) + 3) // 4)
        for i, c in enumerate(bits[odd]):
            b[i >> 2] |= c << ((i & 3) * 2)
        packed.append(bytes(b))

    def rows(vals, per=12, fmt='%5d'):
        out = []
        for i in range(0, len(vals), per):
            out.append('    ' + ' '.join((fmt + ',') % v for v in vals[i:i + per]))
        return '\n'.join(out)

    def bytes_rows(b, per=16):
        out = []
        for i in range(0, len(b), per):
            out.append('    ' + ' '.join('0x%02x,' % v for v in b[i:i + per]))
        return '\n'.join(out)

    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* generated by tools/mkcirc.py from decomp/res/circles.txt --\n'
                '   GDI\'s own circles, see that script and tools/gdicirc.c */\n')
        f.write('#ifndef JW_GEN_CIRCLE_H\n#define JW_GEN_CIRCLE_H\n\n')
        f.write('#define JW_CIRC_RMAX %d\n\n' % RMAX)
        for odd in (0, 1):
            f.write('/* box %s */\n' % ('2r+1' if odd else '2r'))
            f.write('static const unsigned short jw_circ_off%d[JW_CIRC_RMAX + 1] = {\n%s\n};\n'
                    % (odd, rows(off[odd])))
            f.write('static const unsigned short jw_circ_len%d[JW_CIRC_RMAX + 1] = {\n%s\n};\n'
                    % (odd, rows(ln[odd])))
            f.write('static const unsigned char jw_circ_bits%d[%d] = {\n%s\n};\n\n'
                    % (odd, len(packed[odd]), bytes_rows(packed[odd])))
        f.write('#endif\n')
    print('%s: %d + %d steps, %d + %d bytes'
          % (OUT, len(bits[0]), len(bits[1]), len(packed[0]), len(packed[1])))


if __name__ == '__main__':
    main()
