"""Work out which command each toolbar button sends, and bake it in.

    python tools/mkcmd.py            # print the table
    python tools/mkcmd.py --write    # write src/gen/cmds.h

Nothing here is guessed.  src/gen/layout.h says which bitmap strip and which
cell in it each button on the reference screen draws; RT_TOOLBAR for that
strip lists the command ids in the same order, skipping the separators (they
have no image); and the string table holds "what it does\nwhat it is called"
under the command id.  Put together, that is the button's command and the
name printed on it, straight out of the executable.
"""
import re
import sys

LAYOUT = 'src/gen/layout.h'
TOOLBAR = 'decomp/res/toolbar.txt'
STRINGS = 'decomp/res/string.txt'

# 353 is a copy of cell 0 of strip 474 on its own (the two are identical
# pixel for pixel); tools/btnmap.py matched the pressed 線 button to it.
ALIAS = {353: (474, 0)}


def toolbars():
    out, cur = {}, None
    for line in open(TOOLBAR, encoding='utf-8'):
        m = re.match(r'=== TOOLBAR (\d+)', line)
        if m:
            cur = int(m.group(1))
            out[cur] = []
            continue
        m = re.match(r'\s+(\d+) \(0x', line)
        if m and cur is not None:
            out[cur].append(int(m.group(1)))
    return out


def strings():
    out, cur = {}, None
    for line in open(STRINGS, encoding='utf-8'):
        m = re.match(r'\s*(\d+) 0x[0-9a-f]+  (.*)$', line)
        if m:
            cur = int(m.group(1))
            out[cur] = [m.group(2)]
        elif cur is not None and line.strip():
            out[cur].append(line.rstrip('\n'))
    return out


def buttons():
    out = []
    for line in open(LAYOUT, encoding='utf-8'):
        m = re.match(r'\s*\{\s*(-?\d+),\s*(-?\d+),\s*(\d+),\s*(\d+),\s*(\d+)', line)
        if m:
            out.append([int(v) for v in m.groups()])
    return out


def main():
    tb, st, bt = toolbars(), strings(), buttons()
    rows = []
    for x, y, strip, cell, state in bt:
        if strip in ALIAS:
            strip, cell = ALIAS[strip]
        ids = tb.get(strip, [])
        cmd = ids[cell] if cell < len(ids) else 0
        s = st.get(cmd, [''])
        name = s[1] if len(s) > 1 else ''
        rows.append((x, y, strip, cell, state, cmd, name, s[0]))
    if '--write' not in sys.argv:
        for r in rows:
            print('%4d,%4d  strip %3d cell %d  state %d  cmd %5d (0x%04x)  %-10s %s'
                  % (r[0], r[1], r[2], r[3], r[4], r[5], r[5], r[6], r[7]))
        return
    with open('src/gen/cmds.h', 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* Generated by tools/mkcmd.py from RT_TOOLBAR and the string table. */\n')
        f.write('#ifndef JW_CMDS_H\n#define JW_CMDS_H\n\n')
        f.write('/* The command each button on the reference screen sends, in the same\n'
                ' * order as jw_buttons in layout.h.  A button draws pressed when it is\n'
                ' * the current command -- that is what the original\'s\n'
                ' * ON_UPDATE_COMMAND_UI handler (FUN_00511c20) does:\n'
                ' *     pCmdUI->SetCheck(view->current_command == id)\n'
                ' */\n')
        f.write('static const unsigned short jw_btn_cmd[] = {\n')
        for r in rows:
            f.write('    %5d,   /* %s */\n' % (r[5], r[6] or '?'))
        f.write('};\n\n#endif\n')
    print('wrote src/gen/cmds.h')


main()
