#!/usr/bin/env python3
"""Generate src/gen/cp932.h -- the CP932 <-> UTF-16 tables.

Jw_cad 10 saves version 700, and in that version every CString in the file is
UTF-16 (MFC writes 0xff 0xfffe and then the text).  Everything in this port
holds CP932, because that is what the shipped drawings hold and what the
fonts are indexed by, so reading one of those files means converting, and
writing it back again means converting the other way.

The mapping is Windows code page 932's own; this just writes it out.  The
encode direction is taken from the codec rather than by inverting the decode
table, so that the few characters CP932 can spell two ways come back as the
byte pair Windows itself would choose.
"""
import os

dec = {}                        # sjis code -> unicode
for c in range(0x80, 0x100):
    b = bytes([c])
    try:
        u = b.decode('cp932')
    except UnicodeDecodeError:
        continue
    dec[c] = ord(u)
for hi in range(0x81, 0x100):
    for lo in range(0x40, 0x100):
        b = bytes([hi, lo])
        try:
            u = b.decode('cp932')
        except UnicodeDecodeError:
            continue
        if len(u) != 1:
            continue
        dec[(hi << 8) | lo] = ord(u)

enc = {}                        # unicode -> sjis code, the codec's own choice
for u in sorted(set(dec.values())):
    try:
        b = chr(u).encode('cp932')
    except UnicodeEncodeError:
        continue
    enc[u] = b[0] if len(b) == 1 else (b[0] << 8) | b[1]

d = sorted(dec.items())
e = sorted(enc.items())

def rows(vals, per=12):
    out = []
    for i in range(0, len(vals), per):
        out.append('    ' + ' '.join('0x%04x,' % v for v in vals[i:i + per]))
    return '\n'.join(out)

os.makedirs('src/gen', exist_ok=True)
with open('src/gen/cp932.h', 'w', newline='\n') as f:
    f.write('/* generated by tools/mkcp932.py -- code page 932, both ways */\n')
    f.write('#ifndef JW_GEN_CP932_H\n#define JW_GEN_CP932_H\n\n')
    f.write('/* every CP932 code of 0x80 and up, ascending, and what it means */\n')
    f.write('#define JW_CP932_NDEC %d\n' % len(d))
    f.write('static const unsigned short jw_cp932_code[JW_CP932_NDEC] = {\n%s\n};\n\n'
            % rows([k for k, _ in d]))
    f.write('static const unsigned short jw_cp932_uni[JW_CP932_NDEC] = {\n%s\n};\n\n'
            % rows([v for _, v in d]))
    f.write('/* and back: every character CP932 can spell, ascending */\n')
    f.write('#define JW_CP932_NENC %d\n' % len(e))
    f.write('static const unsigned short jw_cp932_wide[JW_CP932_NENC] = {\n%s\n};\n\n'
            % rows([k for k, _ in e]))
    f.write('static const unsigned short jw_cp932_narrow[JW_CP932_NENC] = {\n%s\n};\n\n'
            % rows([v for _, v in e]))
    f.write('#endif\n')
print('src/gen/cp932.h: %d decode, %d encode' % (len(d), len(e)))
