#!/usr/bin/env python3
"""Generate src/gen/dxf.h -- what the original puts at the top of a DXF.

Everything before the entities is the same in every DXF Jw_cad writes except
for eight numbers, so this reads one the original wrote (decomp/res/pens.dxf,
made by tools/refanswers.sh) and keeps it as it is:

  * the HEADER and the VPORT table, cut into the nine pieces that lie between
    those eight numbers -- $EXTMAX and $LIMMAX across and down, $LTSCALE, and
    the viewport's centre and height;
  * the LTYPE and STYLE tables, 7,658 bytes of them, which are the same to
    the byte in every drawing (checked against four).  The first 209 pairs of
    it are orig/DXF_HDR.DAT with the group codes re-aligned; the rest -- the
    ISO line types and Jw_cad's own _ , __18 .. __32 -- is built into the
    program, so the only way to have it is to read one it wrote.

The LAYER table and the entities are the drawing's own and are written by
src/dxf.c.
"""
import io
import os
import sys

SRC = 'decomp/res/pens.dxf'
OUT = 'src/gen/dxf.h'


def pairs(text):
    lines = text.split('\r\n')
    out = []
    for i in range(0, len(lines) - 1, 2):
        out.append((lines[i], lines[i + 1]))
    return out


def carr(name, b):
    """A byte array, so nothing depends on how long a string literal may be."""
    out = ['static const unsigned char %s[] = {' % name]
    row = []
    for i, c in enumerate(b):
        row.append('%d,' % c)
        if len(row) == 20:
            out.append('    ' + ''.join(row))
            row = []
    if row:
        out.append('    ' + ''.join(row))
    out.append('};')
    return '\n'.join(out)


def main():
    raw = io.open(SRC, 'rb').read()
    text = raw.decode('cp932', errors='surrogateescape')

    # the prologue: everything up to the LTYPE table
    i = text.index('  0\r\nTABLE\r\n  2\r\nLTYPE')
    pro = text[:i]
    j = text.index('  0\r\nTABLE\r\n  2\r\nLAYER')
    tabs = text[i:j]

    # cut the prologue at the eight numbers
    p = pairs(pro)
    want = []                   # (index into p, what it is)
    for k in range(len(p)):
        c, v = p[k]
        if c == '  9' and v in ('$EXTMAX', '$LIMMAX'):
            want.append((k + 1, v + '.x'))
            want.append((k + 2, v + '.y'))
        elif c == '  9' and v == '$LTSCALE':
            want.append((k + 1, 'ltscale'))
    # the viewport's centre and height come after the *Active record
    for k in range(len(p)):
        if p[k][0] == '  2' and p[k][1] == '*Active':
            for m in range(k, min(k + 40, len(p))):
                if p[m][0] in (' 12', ' 22', ' 40') and not any(
                        m == w[0] for w in want):
                    want.append((m, 'vport' + p[m][0].strip()))
            break
    want.sort()
    if len(want) != 8:
        print('expected eight numbers, found %d: %s' % (len(want), want),
              file=sys.stderr)
        return 1

    pieces = []
    at = 0
    for k, _ in want:
        piece = ''.join('%s\r\n%s\r\n' % (c, v) for c, v in p[at:k])
        piece += p[k][0] + '\r\n'          # the group code, value next
        pieces.append(piece)
        at = k + 1
    pieces.append(''.join('%s\r\n%s\r\n' % (c, v) for c, v in p[at:]))

    os.makedirs('src/gen', exist_ok=True)
    with io.open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* generated by tools/mkdxf.py from %s --\n'
                '   the part of a DXF that is the original\'s and not the\n'
                '   drawing\'s, see that script */\n' % SRC)
        f.write('#ifndef JW_GEN_DXF_H\n#define JW_GEN_DXF_H\n\n')
        f.write('/* the nine pieces of the header and the viewport table,\n'
                '   with %s\n   between them */\n'
                % ', '.join(w[1] for w in want))
        for n, piece in enumerate(pieces):
            f.write('\n' + carr('jw_dxf_pro%d' % n,
                                piece.encode('cp932', errors='surrogateescape'))
                    + '\n')
        f.write('\nstatic const struct { const unsigned char *b; int n; }\n'
                'jw_dxf_pro[] = {\n')
        for n, piece in enumerate(pieces):
            f.write('    { jw_dxf_pro%d, %d },\n'
                    % (n, len(piece.encode('cp932', errors='surrogateescape'))))
        f.write('};\n#define JW_DXF_NPRO %d\n\n' % len(pieces))
        b = tabs.encode('cp932', errors='surrogateescape')
        f.write('/* the LTYPE and STYLE tables, the same in every drawing */\n')
        f.write(carr('jw_dxf_tables', b) + '\n')
        f.write('#define JW_DXF_NTABLES %d\n\n' % len(b))
        f.write('#endif\n')
    print('%s: %d prologue pieces, %d bytes of tables'
          % (OUT, len(pieces), len(tabs.encode('cp932', errors='surrogateescape'))))
    return 0


if __name__ == '__main__':
    sys.exit(main())
