"""Bake the FONTX2 fonts into C so both builds carry the same bytes.

    python tools/mkfont.py font src/gen

The fonts are public domain (font/PROVENANCE.md); the generated file still
lands in src/gen/ with everything else that is machine output.
"""
import os
import sys


def carray(name, data, per=24):
    out = ['const unsigned char %s[] = {' % name]
    for i in range(0, len(data), per):
        out.append('    ' + ','.join('%d' % b for b in data[i:i + per]) + ',')
    out.append('};')
    out.append('const long %s_len = %d;' % (name, len(data)))
    return '\n'.join(out)


def main():
    src, outdir = sys.argv[1], sys.argv[2]
    os.makedirs(outdir, exist_ok=True)
    ank = open(os.path.join(src, 'JWANK16.FNT'), 'rb').read()
    kan = open(os.path.join(src, 'JWKAN16.FNT'), 'rb').read()

    with open(os.path.join(outdir, 'jwfont.h'), 'w') as f:
        f.write('/* Generated by tools/mkfont.py -- do not edit. */\n'
                '#ifndef JWFONT_H\n#define JWFONT_H\n\n'
                'extern const unsigned char jw_font_ank[];\n'
                'extern const long jw_font_ank_len;\n'
                'extern const unsigned char jw_font_kanji[];\n'
                'extern const long jw_font_kanji_len;\n\n#endif\n')
    with open(os.path.join(outdir, 'jwfont.c'), 'w') as f:
        f.write('/* Generated by tools/mkfont.py from the Shinonome font\n'
                '   (public domain, see font/PROVENANCE.md). */\n')
        f.write('#include "jwfont.h"\n\n')
        f.write(carray('jw_font_ank', ank) + '\n\n')
        f.write(carray('jw_font_kanji', kan) + '\n')
    print('%d + %d bytes -> %s/jwfont.[ch]' % (len(ank), len(kan), outdir))


if __name__ == '__main__':
    main()
