#!/usr/bin/env python3
"""Generate src/gen/grpicon.h -- what the レイヤ設定 dialog draws on 1087.

1087 is 「グループの状態」's button, a BS_BITMAP one like the sixteen
layers', and it shows the state of the group the dialog is looking at.
That is always the group being written to -- the dialog opens on it and
nothing the port does moves it -- so the only state it is ever in is 「書
込み」, and the one thing that changes the picture is whether anything is
drawn on the group.  Hence two pictures, not eight.

They are not the layer icons: the button is bigger (25x21 against 25x21
with a default-button ring, so 21x17 of face inside it instead of 16x14 of
bitmap) and the drawing on it is its own.  Both are lifted whole out of
pictures of the original's dialog:

  docs/ref_layerdlg.png            orig/Test5.jww, whose write group (0)
                                   has 89 things on it
  docs/ref_layerdlg_emptygroup.png tmp/t5wg1.jww, the same drawing with
                                   three longs in its header patched so
                                   that the empty group 1 is the write
                                   group -- tools/probe12.sh

The button is at (105,42) in the client area, which is (8,31) in the
window, and the two rings round it take two pixels, so what is lifted is
the 21x17 from (115,75).
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mklayicon import readpng                       # noqa: E402

W, H = 21, 17
X, Y = 115, 75
AT = [('docs/ref_layerdlg_emptygroup.png', 'nothing drawn on the group'),
      ('docs/ref_layerdlg.png', 'something drawn on it')]


def grab(path):
    w, h, n, px = readpng(path)
    out = []
    for y in range(Y, Y + H):
        for x in range(X, X + W):
            i = (y * w + x) * n
            out.append((px[i] << 16) | (px[i + 1] << 8) | px[i + 2])
    return out


def main():
    cells = []
    for path, _ in AT:
        if not os.path.exists(path):
            print('%s missing' % path, file=sys.stderr)
            return 1
        cells.append(grab(path))
    nl = chr(10)
    f = io.open('src/gen/grpicon.h', 'w', encoding='ascii', newline=nl)
    f.write('/* generated by tools/mkgrpicon.py from pictures of the'
            + nl + "   original's own layer dialog -- see that script */" + nl)
    f.write('#ifndef JW_GEN_GRPICON_H' + nl + '#define JW_GEN_GRPICON_H'
            + nl + nl)
    f.write('#define JW_GRPICON_W %d%s#define JW_GRPICON_H %d%s%s'
            % (W, nl, H, nl, nl))
    f.write('/* [1 if anything is drawn on the write group], inside 1087 */'
            + nl)
    f.write('static const unsigned int jw_grpicon[2][%d] = {%s' % (W * H, nl))
    for cell, (_, what) in zip(cells, AT):
        f.write('  { /* %s */' % what)
        for i, v in enumerate(cell):
            f.write('%s0x%06xu,' % ((nl + '    ') if i % 8 == 0 else ' ', v))
        f.write(nl + '  },' + nl)
    f.write('};' + nl + nl + '#endif' + nl)
    f.close()
    print('src/gen/grpicon.h: 2 cells of %dx%d' % (W, H))
    return 0


if __name__ == '__main__':
    sys.exit(main())
