#!/usr/bin/env python3
"""Bake the program's own 16x16 icon into C.

    python tools/mkicon.py orig/Jw_win.exe src/gen

Jw_win.exe carries fourteen RT_ICON images.  The one Windows puts in the
caption is number 2, 16x16 at 4 bits: laid over the caption of
docs/ref_window.png it matches pixel for pixel, all 256 of them, which is how
it was picked out of the fourteen.

What comes out is the colours and the AND mask, so the browser build can draw
the same caption the native window gets from Windows.
"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rsrc                                             # noqa: E402

WANT = 2                # which RT_ICON, see above
SIZE = 16


def decode(d):
    """An RT_ICON is a DIB: header, palette, colours bottom-up, then mask."""
    w, h, planes, bits = struct.unpack_from('<iiHH', d, 4)
    hdr = struct.unpack_from('<I', d, 0)[0]
    assert w == SIZE and h == 2 * SIZE, (w, h)
    ncol = 1 << bits if bits <= 8 else 0
    pal = [d[hdr + i * 4:hdr + i * 4 + 4] for i in range(ncol)]
    off = hdr + ncol * 4
    stride = ((SIZE * bits + 31) // 32) * 4
    rgb = []
    for row in range(SIZE):
        base = off + row * stride
        line = []
        for col in range(SIZE):
            if bits == 32:
                b, g, r, _a = d[base + col * 4:base + col * 4 + 4]
            elif bits == 8:
                b, g, r, _a = pal[d[base + col]]
            else:
                byte = d[base + col // 2]
                i = (byte >> 4) if col % 2 == 0 else (byte & 15)
                b, g, r, _a = pal[i]
            line.append((r << 16) | (g << 8) | b)
        rgb.append(line)
    # the AND mask: 1 bit per pixel, 1 means "leave what is behind"
    moff = off + SIZE * stride
    mstride = ((SIZE + 31) // 32) * 4
    mask = []
    for row in range(SIZE):
        base = moff + row * mstride
        line = []
        for col in range(SIZE):
            bit = (d[base + col // 8] >> (7 - col % 8)) & 1
            line.append(0 if bit else 1)        # 1 means "draw it"
        mask.append(line)
    return rgb[::-1], mask[::-1]                # DIBs are bottom-up


def main():
    exe, outdir = sys.argv[1], sys.argv[2]
    p = rsrc.PE(exe)
    d = None
    for t, n, lang, rva, sz in p.resources():
        if t == 3 and str(n) == str(WANT):
            d = p.res_data(rva, sz)
    if d is None:
        raise SystemExit('no RT_ICON %s in %s' % (WANT, exe))
    rgb, mask = decode(d)
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, 'jwicon.h'), 'w',
              encoding='ascii', newline='\n') as f:
        f.write('/* Generated by tools/mkicon.py from Jw_win.exe\'s RT_ICON %d\n'
                '   -- the 16x16 the caption shows.  Do not edit. */\n' % WANT)
        f.write('#ifndef JW_GEN_ICON_H\n#define JW_GEN_ICON_H\n\n')
        f.write('#define JW_ICON_W %d\n#define JW_ICON_H %d\n\n' % (SIZE, SIZE))
        f.write('static const unsigned int jw_icon[%d] = {\n' % (SIZE * SIZE))
        for row in rgb:
            f.write('    ' + ' '.join('0x%06xu,' % c for c in row) + '\n')
        f.write('};\n\n')
        f.write('/* 1 where the icon paints, 0 where the caption shows through */\n')
        f.write('static const unsigned char jw_icon_mask[%d] = {\n' % (SIZE * SIZE))
        for row in mask:
            f.write('    ' + ' '.join('%d,' % m for m in row) + '\n')
        f.write('};\n\n#endif\n')
    print('src/gen/jwicon.h: %dx%d from RT_ICON %d' % (SIZE, SIZE, WANT))


if __name__ == '__main__':
    main()
