#!/usr/bin/env python3
"""Generate src/gen/jikkaku.h -- the 軸角・目盛・オフセット dialog (32842's).

The same way as tools/mkzokusel.py: tools/jwdraw.ps1's `dlg:` step sends the
command once a range is in, walks the dialog's children with
EnumChildWindows and writes down each control's class, id, style, text and
rectangle in the dialog's own client coordinates (decomp/res/jikkaku.txt).
It also paints the dialog into a PNG, which is docs/ref_jikkaku.png.

Three group boxes -- 軸角, 目盛 and オフセット -- with a combo in the first
two, a handful of checkboxes and one Ok.

**The angle is typed into the 軸角 combo (1411) and Ok applies it**: the
軸角設定 checkbox beside it is something else, and pressing it takes the
combo away (tools/jwdraw.ps1 cannot find it afterwards), so it has not been
followed up.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkmoji import esc                            # noqa: E402

SRC = 'decomp/res/jikkaku.txt'
OUT = 'src/gen/jikkaku.h'
MASK = 'docs/jikkaku_textareas.txt'

WS_VISIBLE = 0x10000000
BORDER = 8
CAPTION = 31
W, H, CW, CH = 294, 299, 278, 260
TITLE = '軸角・目盛・オフセット　設定'


def kind_of(cid, cls, style):
    if cls == 'Button':
        low = style & 0xf
        if low == 3:                    # BS_AUTOCHECKBOX
            return 'CHECK'
        if low == 7:                    # BS_GROUPBOX
            return 'GROUP'
        return 'OK' if cid in (1, 2) else 'PUSH'
    if cls == 'Edit':
        # 1001 is the one inside a combo box, which is drawn with it
        return None if cid == 1001 else 'EDIT'
    if cls == 'ComboBox':
        return 'COMBO'
    if cls == 'Static':
        return 'STATIC'
    return None


def main():
    rows = []
    for line in io.open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line or line.startswith('==='):
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if not (int(style, 16) & WS_VISIBLE):
            continue
        k = kind_of(int(cid), cls, int(style, 16))
        if k is None:
            continue
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, int(chk),
                     text))

    if not os.path.isdir('src/gen'):
        os.makedirs('src/gen')
    f = io.open(OUT, 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mkjikkaku.py from decomp/res/jikkaku.txt\n'
            '   -- read out of the running original, see that script */\n')
    f.write('#ifndef JW_GEN_JIKKAKU_H\n#define JW_GEN_JIKKAKU_H\n\n')
    f.write('#define JW_JK_W   %d\n' % W)
    f.write('#define JW_JK_H   %d\n' % H)
    f.write('#define JW_JK_CW  %d\n' % CW)
    f.write('#define JW_JK_CH  %d\n' % CH)
    f.write('#define JW_JK_BORDER %d\n' % BORDER)
    f.write('#define JW_JK_CAPTION %d\n' % CAPTION)
    f.write('#define JW_JK_TITLE "%s"\n\n' % esc(TITLE))
    f.write('enum { JW_JK_OK, JW_JK_CHECK, JW_JK_PUSH, JW_JK_STATIC,\n'
            '       JW_JK_COMBO, JW_JK_GROUP, JW_JK_EDIT };\n\n')
    f.write('typedef struct {\n'
            '    short x, y, w, h;      /* the dialog\'s client area */\n'
            '    short id;\n'
            '    unsigned char kind;\n'
            '    unsigned char on;\n'
            '    const char *text;      /* CP932 */\n'
            '} jw_jk_t;\n\n')
    f.write('static const jw_jk_t jw_jikkaku[] = {\n')
    for x, y, ww, hh, cid, k, chk, text in rows:
        f.write('    { %4d, %4d, %4d, %3d, %5d, JW_JK_%-6s, %d, "%s" },\n'
                % (x, y, ww, hh, cid, k, chk, esc(text)))
    f.write('};\n#define JW_NJIKKAKU %d\n\n' % len(rows))
    f.write('#endif\n')
    f.close()

    g = io.open(MASK, 'w', encoding='utf-8', newline='\n')
    g.write('# Where the 軸角 dialog draws text with a Windows font, in\n'
            '# the coordinates of docs/ref_jikkaku.png (the whole %dx%d\n'
            '# window).  The frame and the caption go with them.  Written by\n'
            '# tools/mkjikkaku.py.\n\n' % (W, H))
    g.write('0 0 %d %d\n' % (W, CAPTION))
    g.write('0 %d %d %d\n' % (CAPTION, BORDER, CH))
    g.write('%d %d %d %d\n' % (W - BORDER, CAPTION, BORDER, CH))
    g.write('0 %d %d %d\n' % (H - BORDER, W, BORDER))
    for x, y, ww, hh, cid, k, chk, text in rows:
        x += BORDER
        y += CAPTION
        if k == 'CHECK':
            g.write('%d %d %d %d\n' % (x + 14, y - 1, ww - 13, hh + 2))
        elif k in ('STATIC', 'COMBO', 'EDIT'):
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, hh + 2))
        elif k == 'GROUP':
            # only the strip its label sits in, which is also where the top
            # of its frame runs
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, 17))
        else:
            g.write('%d %d %d %d\n' % (x + 3, y + 3, ww - 6, hh - 6))
    g.close()
    print('%s: %d controls, %s' % (OUT, len(rows), MASK))
    return 0


if __name__ == '__main__':
    sys.exit(main())
