#!/usr/bin/env python3
"""Generate src/gen/jwc.h -- what the original puts at the top of a JWC.

A JWC starts with four 200-byte lines of text and then 1,621 bytes of
settings, and only a handful of numbers in all that belong to the drawing.
So this reads one the original wrote (decomp/res/t5.jwc, made by
tools/refanswers.sh) and keeps the whole 0x975-byte head as it is;
src/jwcwrite.c then puts the drawing's own numbers into it:

  * the drawing's name, two lines of 32 bytes at 0x28;
  * the first line of text, which starts with how many lines, arcs, texts
    and points there are and has the scale tenth;
  * the third, whose second field is how long the run of text is;
  * the sixteen layer group scales, as floats at 0x705;
  * one byte at 0x965, which is the same as the eleventh field of the first
    line.

**Five fields of the first line are not understood** -- the 5th, 6th, 11th,
12th and 19th.  They are the same in every file the original writes out of
the same drawing, and the 19th moves by one for every turn of the wheel, so
it is where the drawing is on screen.  They are kept as they are in the file
this is baked from, which is why the writer's answer is only scored against
drawings that share those settings.  RESUME.md has what is known.
"""
import io
import os
import sys

SRC = 'decomp/res/t5.jwc'
OUT = 'src/gen/jwc.h'
HEAD = 0x975


def carr(name, b):
    out = ['static const unsigned char %s[] = {' % name]
    row = []
    for i, c in enumerate(b):
        row.append('0x%02x,' % c)
        if len(row) == 12:
            out.append('    ' + ''.join(row))
            row = []
    if row:
        out.append('    ' + ''.join(row))
    out.append('};')
    return '\n'.join(out)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else SRC
    out = sys.argv[2] if len(sys.argv) > 2 else OUT
    b = io.open(src, 'rb').read()
    if len(b) < HEAD or b[:13] != b'jw_cad(c)data':
        print('%s is not a JWC' % src)
        return 1
    head = bytearray(b[:HEAD])
    # the name is the drawing's, so it is cleared here rather than baked
    for i in range(0x28, 0x68):
        head[i] = 0
    csv1 = b[0xc8:0xc8 + 200].split(b'\0')[0].decode('cp932')
    csv3 = b[0x258:0x258 + 200].split(b'\0')[0].decode('cp932')
    txt = ['/* Generated by tools/mkjwc.py from %s -- do not edit. */' % src,
           '#ifndef JW_GEN_JWC_H',
           '#define JW_GEN_JWC_H',
           '',
           '#define JWC_HEAD_N 0x%x' % HEAD,
           '#define JWC_NAME   0x28          /* two lines of 32 bytes */',
           '#define JWC_CSV1   0xc8',
           '#define JWC_CSV3   0x258',
           '#define JWC_SCALES 0x705         /* sixteen floats */',
           '#define JWC_PAPER  0x965         /* the first line\'s 11th */',
           '',
           '/* the first and third lines, as the original wrote them: the',
           '   writer replaces the fields it knows and keeps the rest */',
           'static const char JWC_CSV1_TEXT[] = "%s";' % csv1,
           'static const char JWC_CSV3_TEXT[] = "%s";' % csv3,
           '',
           carr('JWC_HEAD', bytes(head)),
           '',
           '#endif']
    d = os.path.dirname(out)
    if d and not os.path.isdir(d):
        os.makedirs(d)
    io.open(out, 'w', encoding='utf-8', newline='\n').write('\n'.join(txt) + '\n')
    print('%s: %d bytes of head, first line %s' % (out, HEAD, csv1[:40]))
    return 0


if __name__ == '__main__':
    sys.exit(main())
