#!/usr/bin/env python3
"""Generate src/gen/kihon.h -- the 基本設定 dialog (32891's).

The same way as the other dialogs: tools/jwdraw.ps1's `dlg:` step sends the
command, walks the children with EnumChildWindows and writes down each
control's class, id, style, text and rectangle in the dialog's own client
coordinates (decomp/res/kihon.txt), and paints the dialog into
docs/ref_kihon.png.

**Only the tab that is on the screen is in the list.**  The dialog has eight
of them and the other seven are not built until they are shown, so this is
一般(1) and nothing else.  Their names are not children either -- they are
items of the SysTabControl32 -- so they are read off the picture and kept
here.

The tab control itself is a themed Windows one and the port draws a plain
one in its place, so the strip across the top goes into the mask with the
caption and the frame.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkmoji import esc                            # noqa: E402

SRC = 'decomp/res/kihon.txt'
OUT = 'src/gen/kihon.h'
MASK = 'docs/kihon_textareas.txt'

WS_VISIBLE = 0x10000000
BORDER = 8
CAPTION = 31
W, H, CW, CH = 624, 635, 608, 596
TITLE = 'jw_win'
TABS = ['一般(1)', '一般(2)', '色・画面', '線種', '文字', 'AUTO', 'KEY',
        'DXF・SFC・JWC']
# where the strip sits, from the SysTabControl32 row
TAB_X, TAB_Y, TAB_W, TAB_H = 7, 8, 594, 547
TAB_ROW = 21                    # how tall the tabs themselves are


def kind_of(cid, cls, style):
    if cls == 'Button':
        low = style & 0xf
        if low == 3:                    # BS_AUTOCHECKBOX
            return 'CHECK'
        if low == 9:                    # BS_AUTORADIOBUTTON
            return 'RADIO'
        return 'PUSH'
    if cls == 'Edit':
        return 'EDIT'
    if cls == 'Static':
        return 'STATIC'
    return None                         # the page and the tab control


def main():
    rows = []
    for line in io.open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line or line.startswith('==='):
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        k = kind_of(int(cid), cls, int(style, 16))
        if k is None:
            continue
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, int(chk),
                     int(en), (int(style, 16) & WS_VISIBLE) != 0, text))

    if not os.path.isdir('src/gen'):
        os.makedirs('src/gen')
    f = io.open(OUT, 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mkkihon.py from decomp/res/kihon.txt --\n'
            '   read out of the running original, see that script */\n')
    f.write('#ifndef JW_GEN_KIHON_H\n#define JW_GEN_KIHON_H\n\n')
    f.write('#define JW_KH_W   %d\n' % W)
    f.write('#define JW_KH_H   %d\n' % H)
    f.write('#define JW_KH_CW  %d\n' % CW)
    f.write('#define JW_KH_CH  %d\n' % CH)
    f.write('#define JW_KH_BORDER %d\n' % BORDER)
    f.write('#define JW_KH_CAPTION %d\n' % CAPTION)
    f.write('#define JW_KH_TITLE "%s"\n' % esc(TITLE))
    f.write('#define JW_KH_TAB_X %d\n#define JW_KH_TAB_Y %d\n'
            '#define JW_KH_TAB_W %d\n#define JW_KH_TAB_H %d\n'
            '#define JW_KH_TAB_ROW %d\n\n'
            % (TAB_X, TAB_Y, TAB_W, TAB_H, TAB_ROW))
    f.write('static const char *const jw_kihon_tabs[] = {\n')
    for t in TABS:
        f.write('    "%s",\n' % esc(t))
    f.write('};\n#define JW_NKIHON_TABS %d\n\n' % len(TABS))
    f.write('enum { JW_KH_CHECK, JW_KH_RADIO, JW_KH_PUSH, JW_KH_STATIC,\n'
            '       JW_KH_EDIT };\n\n')
    f.write('typedef struct {\n'
            '    short x, y, w, h;      /* the dialog\'s client area */\n'
            '    short id;\n'
            '    unsigned char kind;\n'
            '    unsigned char on;      /* how the original had it */\n'
            '    unsigned char enabled;\n'
            '    unsigned char shown;\n'
            '    const char *text;      /* CP932 */\n'
            '} jw_kh_t;\n\n')
    f.write('static const jw_kh_t jw_kihon[] = {\n')
    for x, y, ww, hh, cid, k, chk, en, vis, text in rows:
        f.write('    { %4d, %4d, %4d, %3d, %5d, JW_KH_%-6s, %d, %d, %d,'
                ' "%s" },\n'
                % (x, y, ww, hh, cid, k, chk, en, vis, esc(text)))
    f.write('};\n#define JW_NKIHON %d\n\n' % len(rows))
    f.write('#endif\n')
    f.close()

    g = io.open(MASK, 'w', encoding='utf-8', newline='\n')
    g.write('# Where the 基本設定 dialog draws text with a Windows font, in\n'
            '# the coordinates of docs/ref_kihon.png (the whole %dx%d\n'
            '# window).  The frame, the caption and the tab strip go with\n'
            '# them: Windows draws those itself, the strip with a theme the\n'
            '# port has no copy of.  Written by tools/mkkihon.py.\n\n'
            % (W, H))
    g.write('0 0 %d %d\n' % (W, CAPTION))
    g.write('0 %d %d %d\n' % (CAPTION, BORDER, CH))
    g.write('%d %d %d %d\n' % (W - BORDER, CAPTION, BORDER, CH))
    g.write('0 %d %d %d\n' % (H - BORDER, W, BORDER))
    g.write('%d %d %d %d\n' % (BORDER + TAB_X - 1, CAPTION + TAB_Y - 1,
                               TAB_W + 2, TAB_ROW + 8))
    for x, y, ww, hh, cid, k, chk, en, vis, text in rows:
        x += BORDER
        y += CAPTION
        if k in ('CHECK', 'RADIO'):
            g.write('%d %d %d %d\n' % (x + 14, y - 1, ww - 13, hh + 2))
        elif k in ('STATIC', 'EDIT'):
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, hh + 2))
        else:
            g.write('%d %d %d %d\n' % (x + 3, y + 3, ww - 6, hh - 6))
    g.close()
    print('%s: %d controls, %s' % (OUT, len(rows), MASK))
    return 0


if __name__ == '__main__':
    sys.exit(main())
