#!/usr/bin/env python3
"""Generate src/gen/laytab.h -- the two tab cells of the レイヤ設定 dialog.

The dialog's top half is a tab control (SysTabControl32 1773) with the
sixteen layer groups on it, eight to a row.  It is the only tab control in
anything the port draws, and it is not painted in the same greys as the rest
of the dialog -- the face is f0f0f0 and the edges e3e3e3/a0a0a0/696969,
which is the themed palette rather than the classic one.

Rather than work those rules out, the two cells are lifted whole from a
picture of the original's own dialog (docs/ref_layerdlg.png):

  UNSEL  32 x 16, the THIRD cell of the top row at (74, 33).  The first
         two are not clean: the selected cell of the row below is wider
         than they are and eats into their bottom two rows, where the
         corner of the cell below has to show through
  SEL    36 x 20, the SECOND cell of the bottom row of
         docs/ref_layerdlg_emptygroup.png at (40, 47) -- the group being
         written to in that picture is 1
  SEL0   the same cell at the far left, from docs/ref_layerdlg.png at
         (8, 47), where group 0 is the one being written to.  It is not
         the same: the page's own left edge runs up to meet a cell in the
         first column, so its bottom two corner pixels are the edge and
         not the face

The cells sit 32 apart across and 16 down, and the selected one starts two
earlier on both axes and is drawn last, over its neighbours' edges.

The digit the original had on each of them is painted out again here (the
interior is one flat f0f0f0), because the port writes its own.
"""
import io
import os
import struct
import sys
import zlib


def readpng(path):
    d = io.open(path, 'rb').read()
    o, idat = 8, b''
    w = h = ct = 0
    while o < len(d):
        ln = struct.unpack('>I', d[o:o + 4])[0]
        typ = d[o + 4:o + 8]
        data = d[o + 8:o + 8 + ln]
        o += 12 + ln
        if typ == b'IHDR':
            w, h, _, ct = struct.unpack('>IIBB', data[:10])
        elif typ == b'IDAT':
            idat += data
    raw = zlib.decompress(idat)
    n = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ct]
    stride = w * n
    out = bytearray()
    prev = bytearray(stride)
    i = 0
    for _ in range(h):
        f = raw[i]
        i += 1
        line = bytearray(raw[i:i + stride])
        i += stride
        for x in range(stride):
            a = line[x - n] if x >= n else 0
            b = prev[x]
            c = prev[x - n] if x >= n else 0
            if f == 1:
                line[x] = (line[x] + a) & 255
            elif f == 2:
                line[x] = (line[x] + b) & 255
            elif f == 3:
                line[x] = (line[x] + (a + b) // 2) & 255
            elif f == 4:
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[x] = (line[x] + pr) & 255
        out += line
        prev = line
    return w, h, n, bytes(out)


SRC = 'docs/ref_layerdlg.png'
CELLS = [('UNSEL', 74, 33, 32, 16),
         ('SEL', 40, 47, 36, 20, 'docs/ref_layerdlg_emptygroup.png'),
         ('SEL0', 8, 47, 36, 20)]
FACE = 0xf0f0f0


def grab(px, w, n, x0, y0, cw, ch):
    """The cell, with whatever digit was on it painted out."""
    out = []
    for y in range(y0, y0 + ch):
        for x in range(x0, x0 + cw):
            i = (y * w + x) * n
            v = (px[i] << 16) | (px[i + 1] << 8) | px[i + 2]
            if 2 <= x - x0 < cw - 2 and 3 <= y - y0 < ch - 1:
                v = FACE
            out.append(v)
    return out


def main():
    if not os.path.exists(SRC):
        print('%s missing' % SRC, file=sys.stderr)
        return 1
    w, h, n, px = readpng(SRC)
    f = io.open('src/gen/laytab.h', 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mklaytab.py from a picture of the\n'
            '   original\'s own layer dialog -- see that script */\n')
    f.write('#ifndef JW_GEN_LAYTAB_H\n#define JW_GEN_LAYTAB_H\n\n')
    f.write('/* the cells sit 32 apart across and 16 down, and the first of\n'
            '   the top row has its corner at (2, 2) in the client area */\n')
    f.write('#define JW_LAYTAB_X     2\n')
    f.write('#define JW_LAYTAB_Y     2\n')
    f.write('#define JW_LAYTAB_DX   32\n')
    f.write('#define JW_LAYTAB_DY   16\n')
    for cell in CELLS:
        name, x0, y0, cw, ch = cell[:5]
        if len(cell) > 5:
            cw2, ch2, n2, px2 = readpng(cell[5])
            vals = grab(px2, cw2, n2, x0, y0, cw, ch)
        else:
            vals = grab(px, w, n, x0, y0, cw, ch)
        f.write('\n#define JW_LAYTAB_%s_W %d\n' % (name, cw))
        f.write('#define JW_LAYTAB_%s_H %d\n' % (name, ch))
        f.write('static const unsigned int jw_laytab_%s[%d] = {'
                % (name.lower(), cw * ch))
        for i, v in enumerate(vals):
            f.write('%s0x%06xu,' % ('\n    ' if i % 8 == 0 else ' ', v))
        f.write('\n};\n')
    f.write('\n#endif\n')
    f.close()
    print('src/gen/laytab.h: %d cells' % len(CELLS))
    return 0


if __name__ == '__main__':
    sys.exit(main())
