#!/usr/bin/env python3
"""Generate src/gen/layicon.h -- the eight layer state icons.

The レイヤ設定 dialog draws a small picture on each of its sixteen buttons
instead of a number, and the picture says two things: what state that layer
is in, and whether anything is drawn on it.  A layer with something on it
gets a small dark red mark in its bottom left corner that an empty one does
not, so there are four states times two.

They are bitmaps in the original, and rather than dig them out of the
resources they are lifted straight from pictures of the dialog itself:

  docs/ref_layerdlg.png            orig/Test5.jww as it comes -- layer 8 is
                                   the write layer, the rest 編集可能
  docs/ref_layerdlg_hidden.png     the same with 一括 pressed once (非表示)
  docs/ref_layerdlg_shown.png      and twice (表示のみ)  -- tools/probe11.sh
  docs/ref_layerdlg_emptywrite.png tmp/t5wl5.jww, which is that drawing with
                                   three longs in its header patched so that
                                   the empty layer 5 is the write layer --
                                   tools/probe12.sh, tmp/mkwl5.c

In that drawing layers 0..4 and 8..10 have something on them and 5..7 and
11..15 are empty, which is why layer 0 gives the one and layer 5 the other.

What is lifted is the whole of a button's face -- the 21x17 inside its two
edges -- and not just the bitmap, because the original also draws a grey
band above the bitmap that is part of the button and not of it.  Button
1063 is at (25,135) in the dialog's client area, which is (8,31) in the
window, so its face starts at (35,168).

The write layer's button is drawn pressed and its bitmap sits one pixel
further in, which comes out in the lift because the face is lifted whole.
"""
import io
import os
import struct
import sys
import zlib


def readpng(path):
    d = io.open(path, 'rb').read()
    o, idat = 8, b''
    w = h = ct = 0
    while o < len(d):
        ln = struct.unpack('>I', d[o:o + 4])[0]
        typ = d[o + 4:o + 8]
        data = d[o + 8:o + 8 + ln]
        o += 12 + ln
        if typ == b'IHDR':
            w, h, _, ct = struct.unpack('>IIBB', data[:10])
        elif typ == b'IDAT':
            idat += data
    raw = zlib.decompress(idat)
    n = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ct]
    stride = w * n
    out = bytearray()
    prev = bytearray(stride)
    i = 0
    for _ in range(h):
        f = raw[i]
        i += 1
        line = bytearray(raw[i:i + stride])
        i += stride
        for x in range(stride):
            a = line[x - n] if x >= n else 0
            b = prev[x]
            c = prev[x - n] if x >= n else 0
            if f == 1:
                line[x] = (line[x] + a) & 255
            elif f == 2:
                line[x] = (line[x] + b) & 255
            elif f == 3:
                line[x] = (line[x] + (a + b) // 2) & 255
            elif f == 4:
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[x] = (line[x] + pr) & 255
        out += line
        prev = line
    return w, h, n, bytes(out)


W, H = 21, 17
# Where each face sits.  The first of a pair is layer 0's button, which has
# something on it; the second is layer 5's, which is empty.
X0, Y0 = 35, 168                      # layer 0's face, top left
X5 = X0 + 28 * 5                      # layer 5's, five buttons along
DY = 48                               # and the second row of buttons
AT = {
    'hide':  [('docs/ref_layerdlg_hidden.png', X0, Y0),
              ('docs/ref_layerdlg_hidden.png', X5, Y0)],
    'show':  [('docs/ref_layerdlg_shown.png', X0, Y0),
              ('docs/ref_layerdlg_shown.png', X5, Y0)],
    'edit':  [('docs/ref_layerdlg.png', X0, Y0),
              ('docs/ref_layerdlg.png', X5, Y0)],
    # layer 8 is the write layer in that drawing, layer 5 in the patched one
    'write': [('docs/ref_layerdlg.png', X0, Y0 + DY),
              ('docs/ref_layerdlg_emptywrite.png', X5, Y0)],
}


def grab(path, x0, y0):
    w, h, n, px = readpng(path)
    out = []
    for y in range(y0, y0 + H):
        for x in range(x0, x0 + W):
            i = (y * w + x) * n
            out.append((px[i] << 16) | (px[i + 1] << 8) | px[i + 2])
    return out


def main():
    order = ['hide', 'show', 'edit', 'write']
    icons = {}
    for k in order:
        icons[k] = []
        for path, x, y in AT[k]:
            if not os.path.exists(path):
                print('%s missing' % path, file=sys.stderr)
                return 1
            icons[k].append(grab(path, x, y))
    nl = chr(10)
    f = io.open('src/gen/layicon.h', 'w', encoding='ascii', newline=nl)
    f.write('/* generated by tools/mklayicon.py from pictures of the'
            + nl + "   original's own layer dialog -- see that script */" + nl)
    f.write('#ifndef JW_GEN_LAYICON_H' + nl + '#define JW_GEN_LAYICON_H'
            + nl + nl)
    f.write('#define JW_LAYICON_W %d%s#define JW_LAYICON_H %d%s%s'
            % (W, nl, H, nl, nl))
    f.write('/* [state][1 if anything is drawn on that layer]:' + nl
            + '   0 hidden, 1 shown only, 2 editable, 3 the write layer */'
            + nl)
    f.write('static const unsigned int jw_layicon[4][2][%d] = {%s'
            % (W * H, nl))
    for k in order:
        f.write('  {' + nl)
        for which in (0, 1):            # [0] is the empty one
            f.write('    {')
            for i, v in enumerate(icons[k][1 - which]):
                f.write('%s0x%06xu,' % ((nl + '     ') if i % 8 == 0 else ' ',
                                        v))
            f.write(' },' + nl)
        f.write('  },' + nl)
    f.write('};' + nl + nl + '#endif' + nl)
    f.close()
    print('src/gen/layicon.h: 8 button faces of %dx%d' % (W, H))
    return 0


if __name__ == '__main__':
    sys.exit(main())
