#!/usr/bin/env python3
"""Generate src/gen/layicon.h -- the four layer state icons.

The レイヤ設定 dialog draws a small picture on each of its sixteen buttons
instead of a number, and the picture says what state that layer is in.  They
are bitmaps in the original, and rather than dig them out of the resources
they are lifted straight from pictures of the dialog itself -- the same
dialog, captured with the layers put into each state by its own 一括 button
(tools/probe11.sh).

Each icon is 16 wide and 14 tall and sits at the top left of the button;
button 1063 is at (25,135) in the dialog's client area, which is (8,31) in
the window, and the icon starts three in and four down from there.
"""
import io
import os
import struct
import sys
import zlib


def readpng(path):
    d = io.open(path, 'rb').read()
    o, idat = 8, b''
    w = h = ct = 0
    while o < len(d):
        ln = struct.unpack('>I', d[o:o + 4])[0]
        typ = d[o + 4:o + 8]
        data = d[o + 8:o + 8 + ln]
        o += 12 + ln
        if typ == b'IHDR':
            w, h, _, ct = struct.unpack('>IIBB', data[:10])
        elif typ == b'IDAT':
            idat += data
    raw = zlib.decompress(idat)
    n = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ct]
    stride = w * n
    out = bytearray()
    prev = bytearray(stride)
    i = 0
    for _ in range(h):
        f = raw[i]
        i += 1
        line = bytearray(raw[i:i + stride])
        i += stride
        for x in range(stride):
            a = line[x - n] if x >= n else 0
            b = prev[x]
            c = prev[x - n] if x >= n else 0
            if f == 1:
                line[x] = (line[x] + a) & 255
            elif f == 2:
                line[x] = (line[x] + b) & 255
            elif f == 3:
                line[x] = (line[x] + (a + b) // 2) & 255
            elif f == 4:
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[x] = (line[x] + pr) & 255
        out += line
        prev = line
    return w, h, n, bytes(out)


W, H = 16, 14
# where the icon of layer 0's button sits, and of layer 8's (the one being
# written to in the drawing the pictures were taken of)
AT = {'edit': ('docs/ref_layerdlg.png', 37, 170),
      'hide': ('docs/ref_layerdlg_hidden.png', 37, 170),
      'show': ('docs/ref_layerdlg_shown.png', 37, 170),
      # layer 8 is the one being written to in that drawing, and its
      # button (1071) is the first of the second row
      # layer 8 is the one being written to in that drawing; its button
      # (1071) is the first of the second row and is drawn one pixel
      # over, being the one that is pressed
      'write': ('docs/ref_layerdlg.png', 38, 219)}


def grab(path, x0, y0):
    w, h, n, px = readpng(path)
    out = []
    for y in range(y0, y0 + H):
        for x in range(x0, x0 + W):
            i = (y * w + x) * n
            out.append((px[i] << 16) | (px[i + 1] << 8) | px[i + 2])
    return out


def main():
    order = ['hide', 'show', 'edit', 'write']
    icons = {}
    for k in order:
        path, x, y = AT[k]
        if not os.path.exists(path):
            print('%s missing' % path, file=sys.stderr)
            return 1
        icons[k] = grab(path, x, y)
    f = io.open('src/gen/layicon.h', 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mklayicon.py from pictures of the\n'
            '   original\'s own レイヤ設定 dialog -- see that script */\n'
            .encode('ascii', 'replace').decode('ascii'))
    f.write('#ifndef JW_GEN_LAYICON_H\n#define JW_GEN_LAYICON_H\n\n')
    f.write('#define JW_LAYICON_W %d\n#define JW_LAYICON_H %d\n\n' % (W, H))
    f.write('/* by layer state: 0 hidden, 1 shown only, 2 editable, 3 write */\n')
    f.write('static const unsigned int jw_layicon[4][%d] = {\n' % (W * H))
    for k in order:
        f.write('    {')
        for i, v in enumerate(icons[k]):
            f.write('%s0x%06xu,' % ('\n     ' if i % 8 == 0 else ' ', v))
        f.write(' },\n')
    f.write('};\n\n#endif\n')
    f.close()
    print('src/gen/layicon.h: 4 icons of %dx%d' % (W, H))
    return 0


if __name__ == '__main__':
    sys.exit(main())
