#!/usr/bin/env python3
"""Generate src/gen/layerdlg.h -- the 縮尺・読取 dialog (32808's).

The same way as tools/mkzokusel.py: tools/jwdraw.ps1's `dlg:` step sends the
command once a range is in, walks the dialog's children with
EnumChildWindows and writes down each control's class, id, style, text and
rectangle in the dialog's own client coordinates (decomp/res/layerdlg.txt).
It also paints the dialog into a PNG, which is docs/ref_layerdlg.png.

The sixteen layers of the group being written to: a button for each (1063..
1072, 1115..1119, 1142) with the layer's number on it and a static beside it
(1975..1990) for its name, the group's own state and name at the top, and
全レイヤ編集 / 全レイヤ非表示 / 戻す below.  It is a tabbed dialog
(SysTabControl32 1773), which nothing else here has.

Read out of the running original with `dlg:32808`, which is what the menu's
レイヤ sends and what the status line's third box sends as well.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkmoji import esc                            # noqa: E402

SRC = 'decomp/res/layerdlg.txt'
OUT = 'src/gen/layerdlg.h'
MASK = 'docs/layerdlg_textareas.txt'

WS_VISIBLE = 0x10000000
BORDER = 8
CAPTION = 31
W, H, CW, CH = 294, 410, 278, 371
TITLE = 'レイヤ設定'


def kind_of(cid, cls, style):
    if cls == 'Button':
        low = style & 0xf
        if low == 3:                    # BS_AUTOCHECKBOX
            return 'CHECK'
        if low == 7:                    # BS_GROUPBOX
            return 'GROUP'
        if low == 9:                    # BS_AUTORADIOBUTTON
            return 'RADIO'
        return 'OK' if cid in (1, 2) else 'PUSH'
    if cls == 'Edit':
        # 1001 is the one inside a combo box, which is drawn with it
        return None if cid == 1001 else 'EDIT'
    if cls == 'ComboBox':
        return 'COMBO'
    if cls == 'Static':
        return 'STATIC'
    return None


def main():
    rows = []
    for line in io.open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line or line.startswith('==='):
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if not (int(style, 16) & WS_VISIBLE):
            continue
        # 1839 is painted two rows taller than its window rect
        # says -- the frame round レイヤ名 runs y=271..290 in
        # docs/ref_layerdlg.png, twenty rows, where 1838's runs
        # eighteen.  The rect is what EnumChildWindows handed
        # over; this is what the original actually draws.
        if int(cid) == 1839:
            h = str(int(h) + 2)
        k = kind_of(int(cid), cls, int(style, 16))
        if k is None:
            continue
        # 0x1000 on a static is SS_SUNKEN -- the thin a0a0a0/ffffff frame
        # the original draws round every label in this dialog.  `en` is
        # what IsWindowEnabled said: 戻す (2001) comes up greyed.
        sunk = 1 if (k == 'STATIC' and (int(style, 16) & 0x1000)) else 0
        # BS_DEFPUSHBUTTON: the original rings those in 646464 and
        # a0a0a0 and leaves the 3D edges off -- only 1087 here
        dflt = 1 if (cls == 'Button' and (int(style, 16) & 0xf) == 1) else 0
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, int(chk),
                     int(en), sunk, dflt, text))

    if not os.path.isdir('src/gen'):
        os.makedirs('src/gen')
    f = io.open(OUT, 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mklayerdlg.py from decomp/res/layerdlg.txt\n'
            '   -- read out of the running original, see that script */\n')
    f.write('#ifndef JW_GEN_LAYERDLG_H\n#define JW_GEN_LAYERDLG_H\n\n')
    f.write('#define JW_LD_W   %d\n' % W)
    f.write('#define JW_LD_H   %d\n' % H)
    f.write('#define JW_LD_CW  %d\n' % CW)
    f.write('#define JW_LD_CH  %d\n' % CH)
    f.write('#define JW_LD_BORDER %d\n' % BORDER)
    f.write('#define JW_LD_CAPTION %d\n' % CAPTION)
    f.write('#define JW_LD_TITLE "%s"\n\n' % esc(TITLE))
    f.write('enum { JW_LD_OK, JW_LD_CHECK, JW_LD_PUSH, JW_LD_STATIC,\n'
            '       JW_LD_COMBO, JW_LD_GROUP, JW_LD_EDIT, JW_LD_RADIO };\n\n')
    f.write('typedef struct {\n'
            '    short x, y, w, h;      /* the dialog\'s client area */\n'
            '    short id;\n'
            '    unsigned char kind;\n'
            '    unsigned char on;\n'
            '    unsigned char en;      /* 0 if the original greys it */\n'
            '    unsigned char sunk;    /* SS_SUNKEN: etched frame */\n'
            '    unsigned char dflt;    /* BS_DEFPUSHBUTTON */\n'
            '    const char *text;      /* CP932 */\n'
            '} jw_ld_t;\n\n')
    f.write('static const jw_ld_t jw_layerdlg[] = {\n')
    for x, y, ww, hh, cid, k, chk, en, sunk, dflt, text in rows:
        f.write('    { %4d, %4d, %4d, %3d, %5d, JW_LD_%-6s, %d, %d, %d, %d,'
                ' "%s" },\n'
                % (x, y, ww, hh, cid, k, chk, en, sunk, dflt, esc(text)))
    f.write('};\n#define JW_NLAYERDLG %d\n\n' % len(rows))
    f.write('#endif\n')
    f.close()

    g = io.open(MASK, 'w', encoding='utf-8', newline='\n')
    g.write('# Where the 縮尺 dialog draws text with a Windows font, in\n'
            '# the coordinates of docs/ref_layerdlg.png (the whole %dx%d\n'
            '# window).  The frame and the caption go with them.  Written by\n'
            '# tools/mklayerdlg.py.\n\n' % (W, H))
    g.write('0 0 %d %d\n' % (W, CAPTION))
    g.write('0 %d %d %d\n' % (CAPTION, BORDER, CH))
    g.write('%d %d %d %d\n' % (W - BORDER, CAPTION, BORDER, CH))
    g.write('0 %d %d %d\n' % (H - BORDER, W, BORDER))
    # the sixteen layer-group cells of the tab control: their frames
    # come from pictures of the original's own (tools/mklaytab.py) and
    # are compared, but the digit on each is text and the port's font
    # is not the original's, so the middle of every cell is left out
    for k in range(16):
        tx = BORDER + 2 + 32 * (k & 7)
        ty = CAPTION + 2 + 16 * (0 if k >= 8 else 1)
        g.write('%d %d %d %d' % (tx + 2, ty + 2, 28, 12) + chr(10))
    for x, y, ww, hh, cid, k, chk, en, sunk, dflt, text in rows:
        x += BORDER
        y += CAPTION
        if k in ('CHECK', 'RADIO'):
            g.write('%d %d %d %d\n' % (x + 14, y - 1, ww - 13, hh + 2))
        elif k in ('STATIC', 'COMBO', 'EDIT'):
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, hh + 2))
        elif k == 'GROUP':
            # only the strip its label sits in, which is also where the top
            # of its frame runs
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, 17))
        else:
            # a button: its two edges are compared, the text on it
            # is not -- 一括's reaches to within two of the edge
            g.write('%d %d %d %d\n' % (x + 2, y + 2, ww - 4, hh - 4))
    g.close()
    print('%s: %d controls, %s' % (OUT, len(rows), MASK))
    return 0


if __name__ == '__main__':
    sys.exit(main())
