#!/usr/bin/env python3
"""Generate src/gen/menu.h -- the menu bar, and the whole menu behind it.

    python tools/mkmenu.py

Two things come out of it.

The seven names across the bar, with where each one sits: the names are the
top-level POPUPs of MENU 320 (decomp/res/menu.txt) with the ampersand dropped
the way Windows draws it, and the columns were measured off
docs/ref_window.png -- the original's own window painted into a bitmap.  The
browser has no window of its own, so the port draws that bar itself.

And the whole tree -- every popup, item and separator with the command id it
sends -- so the native build can hand Windows a real menu and get the
original's own one, drawn by Windows and with the popups working.
"""
import os
import re

SRC = 'decomp/res/menu.txt'
OUT = 'src/gen/menu.h'
MENU = '320'            # the frame's menu

# the left edge of each name on the bar, in client pixels, measured off the
# original (docs/ref_window.png)
X = [8, 70, 136, 189, 257, 309, 378]


def esc(s):
    BS = chr(92)
    keep = '"' + BS + '?'
    out = []
    b = s.encode('cp932', 'replace')
    for i, c in enumerate(b):
        if c > 0x7e or c < 0x20 or chr(c) in keep:
            out.append(BS + 'x%02x' % c)
            if i + 1 < len(b) and chr(b[i + 1]) in '0123456789abcdefABCDEF':
                out.append('" "')
        else:
            out.append(chr(c))
    return ''.join(out)


def read():
    """The MENU 320 block, as (depth, kind, id, text) in file order."""
    out = []
    inside = False
    for line in open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        m = re.match(r'^=== MENU (\S+)', line)
        if m:
            inside = m.group(1) == MENU
            continue
        if not inside or not line.strip():
            continue
        depth = (len(line) - len(line.lstrip(' '))) // 2
        t = line.strip()
        if t == 'SEPARATOR':
            out.append((depth, 'sep', 0, ''))
        elif t.startswith('POPUP '):
            out.append((depth, 'popup', 0, t[7:-1]))
        else:
            m = re.match(r'^MENUITEM "(.*)", (\d+) \(', t)
            if m:
                out.append((depth, 'item', int(m.group(2)), m.group(1)))
    return out


def main():
    tree = read()
    tops = [t for t in tree if t[0] == 0 and t[1] == 'popup']
    assert len(tops) >= len(X), tops
    os.makedirs('src/gen', exist_ok=True)
    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* generated by tools/mkmenu.py from decomp/res/menu.txt and\n'
                '   docs/ref_window.png -- see that script */\n')
        f.write('#ifndef JW_GEN_MENU_H\n#define JW_GEN_MENU_H\n\n')
        f.write('/* the bar the port draws for the browser */\n')
        f.write('typedef struct {\n'
                '    short x;               /* where the name starts */\n'
                '    const char *text;      /* CP932 */\n'
                '} jw_menu_t;\n\n')
        f.write('static const jw_menu_t jw_menu[] = {\n')
        for x, t in zip(X, tops):
            f.write('    { %4d, "%s" },\n' % (x, esc(t[3].replace('&', ''))))
        f.write('};\n#define JW_NMENU %d\n\n' % len(X))

        f.write('/* and the whole of it, for the native build to hand to\n'
                '   Windows.  kind: 0 an item, 1 a popup that opens, 2 a\n'
                '   separator; depth is how deep in the tree it sits.  The\n'
                '   text keeps its ampersand -- Windows wants it. */\n')
        f.write('typedef struct {\n'
                '    unsigned char depth, kind;\n'
                '    unsigned short id;\n'
                '    const char *text;      /* CP932 */\n'
                '} jw_menu_item_t;\n\n')
        f.write('static const jw_menu_item_t jw_menu_tree[] = {\n')
        for depth, kind, mid, text in tree:
            k = {'item': 0, 'popup': 1, 'sep': 2}[kind]
            f.write('    { %d, %d, %5d, "%s" },\n'
                    % (depth, k, mid, esc(text)))
        f.write('};\n#define JW_NMENU_TREE %d\n\n#endif\n' % len(tree))
    print('%s: %d on the bar, %d in the tree'
          % (OUT, len(X), len(tree)))


if __name__ == '__main__':
    main()
