#!/usr/bin/env python3
"""Generate src/gen/menu.h -- the menu bar.

    python tools/mkmenu.py

The seven names come out of the menu resource (decomp/res/menu.txt, MENU 320,
its top-level POPUPs) with the ampersand dropped the way Windows draws it.
Where each one sits was measured off docs/ref_window.png, the original's own
window painted into a bitmap: the runs of text in the menu bar start at these
columns of the client area.

The browser has no window of its own, so the port draws this bar itself; the
native build gets a real one from Windows.
"""
import os
import re

SRC = 'decomp/res/menu.txt'
OUT = 'src/gen/menu.h'

# the left edge of each name, in client pixels, measured off the original
X = [8, 70, 136, 189, 257, 309, 378]


def esc(s):
    BS = chr(92)
    keep = '"' + BS + '?'
    out = []
    b = s.encode('cp932')
    for i, c in enumerate(b):
        if c > 0x7e or c < 0x20 or chr(c) in keep:
            out.append(BS + 'x%02x' % c)
            if i + 1 < len(b) and chr(b[i + 1]) in '0123456789abcdefABCDEF':
                out.append('" "')
        else:
            out.append(chr(c))
    return ''.join(out)


def main():
    names = []
    for line in open(SRC, encoding='utf-8'):
        m = re.match(r'^POPUP "(.*)"$', line.rstrip('\n'))
        if m:
            names.append(m.group(1).replace('&', ''))
        if len(names) == len(X):
            break
    assert len(names) == len(X), names
    os.makedirs('src/gen', exist_ok=True)
    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* generated by tools/mkmenu.py from decomp/res/menu.txt and\n'
                '   docs/ref_window.png -- see that script */\n')
        f.write('#ifndef JW_GEN_MENU_H\n#define JW_GEN_MENU_H\n\n')
        f.write('typedef struct {\n'
                '    short x;               /* where the name starts */\n'
                '    const char *text;      /* CP932 */\n'
                '} jw_menu_t;\n\n')
        f.write('static const jw_menu_t jw_menu[] = {\n')
        for x, n in zip(X, names):
            f.write('    { %4d, "%s" },\n' % (x, esc(n)))
        f.write('};\n#define JW_NMENU %d\n\n#endif\n' % len(X))
    print('%s: %d items' % (OUT, len(X)))


if __name__ == '__main__':
    main()
