#!/usr/bin/env python3
"""Generate src/gen/mojikijun.h -- the 文字基点 dialog (文字's 基点 button).

Same way as tools/mkbairitsu.py: tools/jwdraw.ps1's `dlg:b` step presses
the button, walks the dialog's children with EnumChildWindows and writes
down each control's class, id, style, text and rectangle in the dialog's
own client coordinates (decomp/res/mojikijun.txt, taken by
tools/probe62.sh).  It also paints the dialog into a PNG, which is
docs/ref_mojikijun.png.

What the dialog holds:

  * a 3x3 of radios, 1689..1697, in the order 左上 左中 左下 中上 中中
    中下 右上 右中 右下, inside a 文字基点 group box.  左下 is the one it
    comes up on, and what each of the nine does to a placed text was
    measured off the original in tools/probe62.sh -- see the note by
    moji_kijun in src/cmd.c.
  * ずれ使用 (1323) with six edit boxes, three across the bottom for the
    横ずれ and three up the left for the 縦ずれ.  They come up **greyed**
    (their style has no WS_DISABLED set but the capture says enabled=0),
    which is what ずれ使用 turns on.
  * 下線作図 (1327), 上線作図 (1328), 左右縦線 (1329)
  * 文字横方向 (1325), 文字縦方向 (1326) and the 文字移動 label (1998),
    which are **not visible** as the dialog comes up -- their style has no
    WS_VISIBLE -- so they are left out, the way the other generators leave
    out the second set a bar carries.

Only the nine radios are wired up in the port; the rest is drawn so the
dialog is the original's picture, and what they do has not been asked.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkmoji import esc                            # noqa: E402

SRC = 'decomp/res/mojikijun.txt'
OUT = 'src/gen/mojikijun.h'
MASK = 'docs/mojikijun_textareas.txt'

WS_VISIBLE = 0x10000000
BORDER = 8
CAPTION = 31
W, H, CW, CH = 255, 239, 239, 200
TITLE = '文字基点設定'


def kind_of(cid, cls, style):
    if cls == 'Button':
        low = style & 0xf
        if low == 3:                    # BS_AUTOCHECKBOX
            return 'CHECK'
        if low == 7:                    # BS_GROUPBOX
            return 'GROUP'
        if low == 9:                    # BS_AUTORADIOBUTTON
            return 'RADIO'
        return 'OK' if cid in (1, 2) else 'PUSH'
    if cls == 'Edit':
        return None if cid == 1001 else 'EDIT'
    if cls == 'ComboBox':
        return 'COMBO'
    if cls == 'Static':
        return 'STATIC'
    return None


def main():
    rows = []
    for line in io.open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line or line.startswith('==='):
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if not (int(style, 16) & WS_VISIBLE):
            continue
        k = kind_of(int(cid), cls, int(style, 16))
        if k is None:
            continue
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, int(chk),
                     (int(style, 16) & 0xf) == 1, int(en), text))

    if not os.path.isdir('src/gen'):
        os.makedirs('src/gen')
    f = io.open(OUT, 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mkmojikijun.py from '
            'decomp/res/mojikijun.txt\n'
            '   -- read out of the running original, see that script */\n')
    f.write('#ifndef JW_GEN_MOJIKIJUN_H\n#define JW_GEN_MOJIKIJUN_H\n\n')
    f.write('#define JW_MK_W   %d\n' % W)
    f.write('#define JW_MK_H   %d\n' % H)
    f.write('#define JW_MK_CW  %d\n' % CW)
    f.write('#define JW_MK_CH  %d\n' % CH)
    f.write('#define JW_MK_BORDER %d\n' % BORDER)
    f.write('#define JW_MK_CAPTION %d\n' % CAPTION)
    f.write('#define JW_MK_TITLE "%s"\n\n' % esc(TITLE))
    f.write('enum { JW_MK_OK, JW_MK_CHECK, JW_MK_PUSH, JW_MK_STATIC,\n'
            '       JW_MK_COMBO, JW_MK_GROUP, JW_MK_EDIT, JW_MK_RADIO };\n\n')
    f.write('typedef struct {\n'
            '    short x, y, w, h;      /* the dialog\'s client area */\n'
            '    short id;\n'
            '    unsigned char kind;\n'
            '    unsigned char on;\n'
            '    unsigned char deflt;   /* BS_DEFPUSHBUTTON */\n'
            '    unsigned char enabled;\n'
            '    const char *text;      /* CP932 */\n'
            '} jw_mk_t;\n\n')
    f.write('static const jw_mk_t jw_mojikijun[] = {\n')
    for x, y, ww, hh, cid, k, chk, dft, en, text in rows:
        f.write('    { %4d, %4d, %4d, %3d, %5d, JW_MK_%-6s, %d, %d, %d,'
                ' "%s" },\n'
                % (x, y, ww, hh, cid, k, chk, dft, en, esc(text)))
    f.write('};\n#define JW_NMOJIKIJUN %d\n\n' % len(rows))
    f.write('#endif\n')
    f.close()

    g = io.open(MASK, 'w', encoding='utf-8', newline='\n')
    g.write('# Where the 文字基点 dialog draws text with a Windows font, in\n'
            '# the coordinates of docs/ref_mojikijun.png (the whole %dx%d\n'
            '# window).  The frame and the caption go with them.  Written by\n'
            '# tools/mkmojikijun.py.\n\n' % (W, H))
    g.write('0 0 %d %d\n' % (W, CAPTION))
    g.write('0 %d %d %d\n' % (CAPTION, BORDER, CH))
    g.write('%d %d %d %d\n' % (W - BORDER, CAPTION, BORDER, CH))
    g.write('0 %d %d %d\n' % (H - BORDER, W, BORDER))
    for x, y, ww, hh, cid, k, chk, dft, en, text in rows:
        x += BORDER
        y += CAPTION
        if k in ('CHECK', 'RADIO'):
            g.write('%d %d %d %d\n' % (x + 14, y - 1, ww - 13, hh + 2))
        elif k in ('STATIC', 'COMBO', 'EDIT'):
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, hh + 2))
        elif k == 'GROUP':
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, 17))
        else:
            n = 3 if dft else 2
            g.write('%d %d %d %d\n' % (x + n, y + n, ww - 2 * n, hh - 2 * n))
    g.close()
    print('%s: %d controls, %s' % (OUT, len(rows), MASK))
    return 0


if __name__ == '__main__':
    sys.exit(main())
