"""Bake the original's own new drawing into C.

    python tools/mknew.py decomp/res/new.jww src/gen

decomp/res/new.jww is what Jw_cad 10.03.6 itself saves when it is started
with no file and told to save at once, in the reference environment
(tools/refenv.sh).  It is an empty drawing: no elements of its own, only the
six hidden text records Jw_cad writes its printer and view settings into.

A new drawing in the port is that file, read back.  Everything a saved file
needs -- the sixteen layer groups, the pen table, the line types, the hatch
and dimension settings, the text styles -- is then the original's, not a
guess, and the header comes with it, so a drawing started from scratch can be
saved and opened again in Jw_cad.
"""
import os
import sys


def main():
    src, outdir = sys.argv[1], sys.argv[2]
    b = open(src, 'rb').read()
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, 'newjww.h'), 'w', newline='\n') as f:
        f.write('/* Generated by tools/mknew.py -- do not edit. */\n'
                '#ifndef JW_GEN_NEWJWW_H\n#define JW_GEN_NEWJWW_H\n\n'
                '/* Jw_cad 10.03.6\'s own empty drawing, see tools/mknew.py */\n'
                'extern const unsigned char jw_new_jww[];\n'
                'extern const long jw_new_jww_len;\n\n#endif\n')
    with open(os.path.join(outdir, 'newjww.c'), 'w', newline='\n') as f:
        f.write('/* Generated by tools/mknew.py from decomp/res/new.jww. */\n')
        f.write('#include "newjww.h"\n\n')
        f.write('const unsigned char jw_new_jww[] = {\n')
        for i in range(0, len(b), 24):
            f.write('    ' + ','.join('%d' % c for c in b[i:i + 24]) + ',\n')
        f.write('};\n')
        f.write('const long jw_new_jww_len = %d;\n' % len(b))
    print('%d bytes -> %s/newjww.[ch]' % (len(b), outdir))


if __name__ == '__main__':
    main()
