"""Bake the original's own defaults for a drawing that has just been started.

    python tools/mkpen.py

There is no file to read them from when nothing has been opened, so they come
from where the original keeps them: the HKCU Jw_cad settings, saved in
tools/refenv.reg.  Pen/ColorNN is a COLORREF (0x00bbggrr) and PenStyle has
nothing to do with the screen.  The sheet and the scale are checked against
docs/ref_start.png, whose status line reads "A-2  S=1/100  [0-0]".
"""
import io
import re

REG = 'tools/refenv.reg'
OUT = 'src/gen/pens.h'


def read():
    out, cur = {}, None
    for line in io.open(REG, encoding='utf-16', errors='replace'):
        line = line.strip()
        if line.startswith('['):
            cur = line[1:-1].split(chr(92))[-1]
            out[cur] = {}
        elif cur and '=' in line:
            k, v = line.split('=', 1)
            out[cur][k.strip('"')] = v.strip()
    return out


def val(s):
    if s.startswith('dword:'):
        return int(s[6:], 16)
    return s.strip('"')


def main():
    r = read()
    pen = r['Pen']
    scr = r['Screen']
    rows = []
    for i in range(10):
        c = int(val(pen.get('Color%02d' % i, '"0"')) or '0', 16)
        w = int(val(pen.get('Width%02d' % i, '"1"')) or '1')
        rgb = ((c & 0xff) << 16) | (c & 0xff00) | ((c >> 16) & 0xff)
        rows.append((rgb, w))
    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* Generated by tools/mkpen.py from the original\'s own settings. */\n')
        f.write('#ifndef JW_PENS_H\n#define JW_PENS_H\n\n')
        f.write('/* The ten screen pens, as 0x00rrggbb.  The registry keeps them the\n'
                ' * way GDI does, 0x00bbggrr, under Pen/ColorNN. */' + chr(10))
        f.write('static const unsigned int jw_default_pen_rgb[10] = {\n')
        for rgb, _ in rows:
            f.write('    0x%06xu,\n' % rgb)
        f.write('};\n\n')
        f.write('static const int jw_default_pen_width[10] = {\n    ')
        f.write(', '.join(str(w) for _, w in rows))
        f.write('\n};\n\n')
        sel = int(val(pen.get('Color10', '"ff00ff"')) or '0', 16)
        rng = int(val(pen.get('Color11', '"ff"')) or '0', 16)
        bgr = lambda c: ((c & 0xff) << 16) | (c & 0xff00) | ((c >> 16) & 0xff)
        f.write('/* Two colours that are in no drawing: the one a picked element is\n')
        f.write(' * drawn in and the one the range box is drawn in.  Pen/Color10 and\n')
        f.write(' * Color11 -- and the original bears them out: a range dragged over\n')
        f.write(' * Test5, with the window painted into an off-screen bitmap, has the\n')
        f.write(' * picked lines in ff00ff and the box in ff0000. */\n')
        f.write('#define JW_SEL_RGB    0x%06xu\n' % bgr(sel))
        f.write('#define JW_RANGE_RGB  0x%06xu\n\n' % bgr(rng))
        f.write('/* A drawing that has just been started.  The status line of\n'
                ' * docs/ref_start.png reads "A-2  S=1/100  [0-0]", which is these\n'
                ' * three: sheet index 2, the write group\'s scale, and group 0 /\n'
                ' * layer 0 being the ones written to. */\n')
        f.write('#define JW_NEW_PAPER  %d\n' % int(val(scr.get('PaperSize', 'dword:00000002'))))
        f.write('#define JW_NEW_SCALE  %s\n' % val(scr.get('Scale', '"100"')))
        f.write('#define JW_NEW_LAYER  %d\n' % int(val(r['Init'].get('Lay', 'dword:00000000'))))
        f.write('\n#endif\n')
    print('wrote', OUT)


main()
