"""Bake Jw_win.exe's resources into C the port can compile in.

The generated files are machine output from someone else's program, so they
land in src/gen/ and are not committed -- rebuild them from your own copy:

    python tools/mkres.py orig/Jw_win.exe src/gen [--maxh 19]

Bitmaps come out as one byte per pixel (the 4bpp DIB unpacked, top-down, no
row padding) plus the 16-entry palette that belongs to them; there are four
different palettes in the file, so they cannot be shared.
"""
import argparse
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pe import PE

RT_BITMAP = 2
RT_TOOLBAR = 241


def unpack_dib(d):
    """(w, h, palette[16*(r,g,b)], indices top-down) from a BITMAPINFO blob."""
    hdrsz = struct.unpack_from('<I', d, 0)[0]
    w, h = struct.unpack_from('<ii', d, 4)
    bits = struct.unpack_from('<H', d, 14)[0]
    comp = struct.unpack_from('<I', d, 16)[0]
    nclr = struct.unpack_from('<I', d, 32)[0] or (1 << bits)
    if bits != 4 or comp != 0:
        raise ValueError('only uncompressed 4bpp handled, got %dbpp comp=%d'
                         % (bits, comp))
    pal = []
    o = hdrsz
    for i in range(16):
        b, g, r = d[o + 4 * i], d[o + 4 * i + 1], d[o + 4 * i + 2]
        pal.append((r, g, b))
    o += 4 * nclr
    bottom_up = h > 0
    h = abs(h)
    stride = ((w * 4 + 31) // 32) * 4
    out = bytearray(w * h)
    for y in range(h):
        src = o + (h - 1 - y if bottom_up else y) * stride
        row = d[src:src + stride]
        for x in range(w):
            byte = row[x >> 1]
            out[y * w + x] = (byte >> 4) if (x & 1) == 0 else (byte & 15)
    return w, h, pal, bytes(out)


def carray(name, data, per=24):
    out = ['static const unsigned char %s[] = {' % name]
    for i in range(0, len(data), per):
        out.append('    ' + ','.join('%d' % b for b in data[i:i + per]) + ',')
    out.append('};')
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('exe')
    ap.add_argument('outdir')
    ap.add_argument('--maxh', type=int, default=19,
                    help='skip bitmaps taller than this (the big toolbar '
                         'sizes are the same art again and cost 1.9 MB)')
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    pe = PE(args.exe)
    res = pe.resources()
    bitmaps, toolbars = [], []
    for t, n, lang, rva, sz in sorted(res, key=lambda r: str(r[1])):
        if not isinstance(n, int):
            continue
        d = pe.res_data(rva, sz)
        if t == RT_BITMAP:
            try:
                w, h, pal, idx = unpack_dib(d)
            except ValueError as e:
                print('skip BITMAP %s: %s' % (n, e))
                continue
            if h > args.maxh:
                continue
            bitmaps.append((n, w, h, pal, idx))
        elif t == RT_TOOLBAR:
            ver, w, h, cnt = struct.unpack_from('<HHHH', d, 0)
            ids = struct.unpack_from('<%dH' % cnt, d, 8)
            toolbars.append((n, w, h, ids))

    bitmaps.sort()
    toolbars.sort()

    h = ['/* Generated by tools/mkres.py -- do not edit, do not commit. */',
         '#ifndef JWRES_H', '#define JWRES_H', '',
         'typedef struct {',
         '    int id, w, h;',
         '    const unsigned char *pal;   /* 16 * 3 bytes, r,g,b */',
         '    const unsigned char *idx;   /* w*h, top-down, one byte a pixel */',
         '} jw_bitmap_t;', '',
         'typedef struct {',
         '    int id, w, h, n;',
         '    const unsigned short *ids;  /* 0 is a separator */',
         '} jw_toolbar_t;', '',
         'extern const jw_bitmap_t jw_bitmaps[];',
         'extern const int jw_nbitmaps;',
         'extern const jw_toolbar_t jw_toolbars[];',
         'extern const int jw_ntoolbars;', '',
         'const jw_bitmap_t *jw_bitmap(int id);',
         'const jw_toolbar_t *jw_toolbar(int id);', '',
         '#endif']
    open(args.outdir + '/jwres.h', 'w').write('\n'.join(h) + '\n')

    c = ['/* Generated by tools/mkres.py -- do not edit, do not commit. */',
         '#include "jwres.h"', '']
    for n, w, hh, pal, idx in bitmaps:
        flat = bytes(b for rgb in pal for b in rgb)
        c.append(carray('pal_%d' % n, flat, 24))
        c.append(carray('bmp_%d' % n, idx, 32))
        c.append('')
    c.append('const jw_bitmap_t jw_bitmaps[] = {')
    for n, w, hh, pal, idx in bitmaps:
        c.append('    { %d, %d, %d, pal_%d, bmp_%d },' % (n, w, hh, n, n))
    c.append('};')
    c.append('const int jw_nbitmaps = %d;' % len(bitmaps))
    c.append('')
    for n, w, hh, ids in toolbars:
        c.append('static const unsigned short tb_%d[] = {%s};'
                 % (n, ','.join(str(i) for i in ids)))
    c.append('const jw_toolbar_t jw_toolbars[] = {')
    for n, w, hh, ids in toolbars:
        c.append('    { %d, %d, %d, %d, tb_%d },' % (n, w, hh, len(ids), n))
    c.append('};')
    c.append('const int jw_ntoolbars = %d;' % len(toolbars))
    c.append('')
    c.append('const jw_bitmap_t *jw_bitmap(int id)')
    c.append('{')
    c.append('    int i;')
    c.append('    for (i = 0; i < jw_nbitmaps; i++)')
    c.append('        if (jw_bitmaps[i].id == id) return &jw_bitmaps[i];')
    c.append('    return 0;')
    c.append('}')
    c.append('')
    c.append('const jw_toolbar_t *jw_toolbar(int id)')
    c.append('{')
    c.append('    int i;')
    c.append('    for (i = 0; i < jw_ntoolbars; i++)')
    c.append('        if (jw_toolbars[i].id == id) return &jw_toolbars[i];')
    c.append('    return 0;')
    c.append('}')
    open(args.outdir + '/jwres.c', 'w').write('\n'.join(c) + '\n')

    px = sum(w * hh for _, w, hh, _, _ in bitmaps)
    print('%d bitmaps (%d px), %d toolbars -> %s/jwres.[ch]'
          % (len(bitmaps), px, len(toolbars), args.outdir))


if __name__ == '__main__':
    main()
