#!/usr/bin/env python3
"""Generate src/gen/skradio.h -- the two radio buttons of 縮尺・読取　設定.

The port already has a pair lifted from the 書込み文字種変更 dialog
(src/gen/moji.h, jw_moji_radio_on/off), but this dialog's are not the same
picture: they are drawn in the themed greys, a0a0a0 and 696969 round the
ring with e3e3e3 for the shadow inside it, where 文字's are the classic
ones.  So they are lifted from a picture of this dialog instead.

  docs/ref_shakudo.png, painted by Jw_cad itself over orig/Test5.jww

1704 (実寸固定) is the one that is on and 1705 (図寸固定) the one that is
off.  They are at (224,83) and (341,83) in the client area, which is (8,31)
in the window, and what is lifted is the 13x14 at the control's own corner
-- the ring itself takes eleven by twelve of that, one in and one down.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mklayicon import readpng                       # noqa: E402

SRC = 'docs/ref_shakudo.png'
W, H = 13, 14
AT = [('ON', 232, 114), ('OFF', 349, 114)]


def grab(px, w, n, x0, y0):
    out = []
    for y in range(y0, y0 + H):
        for x in range(x0, x0 + W):
            i = (y * w + x) * n
            out.append((px[i] << 16) | (px[i + 1] << 8) | px[i + 2])
    return out


def main():
    if not os.path.exists(SRC):
        print('%s missing' % SRC, file=sys.stderr)
        return 1
    w, h, n, px = readpng(SRC)
    nl = chr(10)
    f = io.open('src/gen/skradio.h', 'w', encoding='ascii', newline=nl)
    f.write('/* generated by tools/mkskradio.py from a picture of the'
            + nl + "   original's own scale dialog -- see that script */" + nl)
    f.write('#ifndef JW_GEN_SKRADIO_H' + nl + '#define JW_GEN_SKRADIO_H'
            + nl + nl)
    f.write('#define JW_SKRADIO_W %d%s#define JW_SKRADIO_H %d%s%s'
            % (W, nl, H, nl, nl))
    for name, x0, y0 in AT:
        vals = grab(px, w, n, x0, y0)
        f.write('static const unsigned int jw_skradio_%s[%d] = {%s'
                % (name.lower(), W * H, nl))
        for i, v in enumerate(vals):
            f.write('%s0x%06xu,' % ((nl + '    ') if i % 8 == 0 else ' ', v))
        f.write(nl + '};' + nl + nl)
    f.write('#endif' + nl)
    f.close()
    print('src/gen/skradio.h: two %dx%d' % (W, H))
    return 0


if __name__ == '__main__':
    sys.exit(main())
