"""Bake chosen strings out of the original's string table.

    python tools/mkstr.py

The status line's prompts are string-table entries: the 線 command shows
5320 while it waits for the first point and 5321 while it waits for the
second (CZukeiSen calls FUN_004efbb0(0x14c8) and (0x14c9) at those two
points), 点 shows 5376 (CZukeiTen, FUN_004efbb0(0x1500)), and 円 shows 5309
then 5301 (CZukeiEnko, FUN_004efbb0(0x14bd) and (0x14b5)), and 消去 shows
10111 (CZukeiShoukyo, FUN_004efbb0(0x277f)), which is also where the two
buttons' jobs are written down: (L) is a partial erase, (R) deletes the
whole element.  They are written out as CP932 bytes because that is how the font
is indexed, and as escapes so this file stays plain ASCII.
"""
WANT = [
    (5320, 'the first point of a line'),
    (5321, 'the second point of a line'),
    (5376, 'where to put a point'),
    (5309, 'the centre of a circle'),
    (5301, 'a point the circle passes through'),
    (10111, 'what the two buttons do when erasing'),
    (10112, 'the first end of the piece to take out of a line'),
    (10113, 'the second end of it'),
    (10114, 'the first end of the piece to take out of a circle'),
    (10115, 'the second end of it'),
    (5340, 'the first line of a corner'),
    (5341, 'the second line of it'),
    (5336, 'the line to stretch or shorten'),
    (5338, 'where its end should go'),
    (5305, 'the line to make a parallel of'),
    (5366, 'which side to put it'),
    (5263, 'the element to take the pen and layer from'),
    (5316, 'before anything is typed'),
    (5318, 'where the typed text goes'),
    (5383, 'the first corner of a range'),
    (5326, 'the second one -- the right button takes the texts too'),
    (5314, 'the point a copy or a move is measured from'),
    (5307, 'where the copy goes'),
    (5311, 'where the move goes'),
    (5329, 'a dimension: where its extension lines start'),
    (5330, 'where its line goes'),
    (5331, 'the first point it measures'),
    (5332, 'the second'),
]

STRINGS = 'decomp/res/string.txt'
OUT = 'src/gen/prompts.h'


def strings():
    import re
    out, cur = {}, None
    for line in open(STRINGS, encoding='utf-8'):
        m = re.match(r'\s*(\d+) 0x[0-9a-f]+  (.*)$', line)
        if m:
            cur = int(m.group(1))
            out[cur] = m.group(2)
        elif cur is not None and line.strip():
            pass          # the second line is the tooltip, not wanted here
    return out


def esc(s):
    BS = chr(92)
    keep = '"' + BS + '?'
    out = []
    b = s.encode('cp932')
    for i, c in enumerate(b):
        if c > 0x7e or c < 0x20 or chr(c) in keep:
            out.append(BS + 'x%02x' % c)
            # C eats as many hex digits as it can, so stop the escape
            # if a hex digit comes next
            if i + 1 < len(b) and chr(b[i + 1]) in '0123456789abcdefABCDEF':
                out.append('" "')
        else:
            out.append(chr(c))
    return ''.join(out)


def main():
    st = strings()
    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* Generated by tools/mkstr.py from the original\'s string table. */\n')
        f.write('#ifndef JW_PROMPTS_H\n#define JW_PROMPTS_H\n\n')
        f.write('/* CP932, which is how src/text.c indexes the font. */\n')
        for num, what in WANT:
            f.write('/* %d: %s */\n' % (num, what))
            f.write('#define JW_STR_%d "%s"\n' % (num, esc(st[num])))
        f.write('\n#endif\n')
    print('wrote', OUT)
    for num, _ in WANT:
        print(' %d %s' % (num, st[num]))


main()
