"""Bake chosen strings out of the original's string table.

    python tools/mkstr.py

The status line's prompts are string-table entries: the 線 command shows
5320 while it waits for the first point and 5321 while it waits for the
second (CZukeiSen calls FUN_004efbb0(0x14c8) and (0x14c9) at those two
points), and 点 shows 5376 (CZukeiTen, FUN_004efbb0(0x1500)).  They are written out as CP932 bytes because that is how the font
is indexed, and as escapes so this file stays plain ASCII.
"""
WANT = [
    (5320, 'the first point of a line'),
    (5321, 'the second point of a line'),
    (5376, 'where to put a point'),
]

STRINGS = 'decomp/res/string.txt'
OUT = 'src/gen/prompts.h'


def strings():
    import re
    out, cur = {}, None
    for line in open(STRINGS, encoding='utf-8'):
        m = re.match(r'\s*(\d+) 0x[0-9a-f]+  (.*)$', line)
        if m:
            cur = int(m.group(1))
            out[cur] = m.group(2)
        elif cur is not None and line.strip():
            pass          # the second line is the tooltip, not wanted here
    return out


def esc(s):
    BS = chr(92)
    keep = '"' + BS + '?'
    out = []
    b = s.encode('cp932')
    for i, c in enumerate(b):
        if c > 0x7e or c < 0x20 or chr(c) in keep:
            out.append(BS + 'x%02x' % c)
            # C eats as many hex digits as it can, so stop the escape
            # if a hex digit comes next
            if i + 1 < len(b) and chr(b[i + 1]) in '0123456789abcdefABCDEF':
                out.append('" "')
        else:
            out.append(chr(c))
    return ''.join(out)


def main():
    st = strings()
    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* Generated by tools/mkstr.py from the original\'s string table. */\n')
        f.write('#ifndef JW_PROMPTS_H\n#define JW_PROMPTS_H\n\n')
        f.write('/* CP932, which is how src/text.c indexes the font. */\n')
        for num, what in WANT:
            f.write('/* %d: %s */\n' % (num, what))
            f.write('#define JW_STR_%d "%s"\n' % (num, esc(st[num])))
        f.write('\n#endif\n')
    print('wrote', OUT)
    for num, _ in WANT:
        print(' %d %s' % (num, st[num]))


main()
