"""Bake the original's dimension settings.

    python tools/mksunpo.py

They live in HKCU Jw_cad jw_win/SUNPO, saved in tools/refenv.reg, and every
one of them shows up in what the original actually draws.  A dimension was
made in Jw_cad and the file read back (see RESUME.md); it came out as

    dimension line   CDataSen  colour SENColor,      flags 0x2000
    terminators      CDataTen x2 at its ends, colour TENColor, flags 0x0040
    extension lines  CDataSen x2, colour HIKIDASHIColor, flags 0x2000
    the value        CDataMoji, text style MOJINO, HANARE above the line, flags 0x4010

so these are the numbers the port has to draw with.
"""
import io

REG = 'tools/refenv.reg'
OUT = 'src/gen/sunpo.h'


def read():
    out, cur = {}, None
    for line in io.open(REG, encoding='utf-16', errors='replace'):
        line = line.strip()
        if line.startswith('['):
            cur = line[1:-1].split(chr(92))[-1]
            out[cur] = {}
        elif cur and '=' in line:
            k, v = line.split('=', 1)
            out[cur][k.strip('"')] = v.strip()
    return out


def val(s):
    if s.startswith('dword:'):
        return int(s[6:], 16)
    return s.strip('"')


def main():
    s = read()['SUNPO']
    d = lambda k: int(val(s[k]))
    f = lambda k: float(val(s[k]))
    with open(OUT, 'w', encoding='ascii', newline='\n') as o:
        o.write('/* Generated by tools/mksunpo.py from the original\'s own\n'
                '   settings -- see that script. */\n')
        o.write('#ifndef JW_GEN_SUNPO_H\n#define JW_GEN_SUNPO_H\n\n')
        o.write('/* colours (pen numbers) */\n')
        o.write('#define JW_SUN_SEN_COLOR   %d\n' % d('SENColor'))
        o.write('#define JW_SUN_HIKI_COLOR  %d\n' % d('HIKIDASHIColor'))
        o.write('#define JW_SUN_TEN_COLOR   %d\n' % d('TENColor'))
        o.write('/* the text style for the value, 1..10 */\n')
        o.write('#define JW_SUN_MOJINO      %d\n' % d('MOJINO'))
        o.write('/* how far above the dimension line the value sits, in mm */\n')
        o.write('#define JW_SUN_HANARE      %g\n' % f('HANARE'))
        o.write('/* how far the extension line runs past the dimension line */\n')
        o.write('#define JW_SUN_TSUKIDASHI  %g\n' % f('TSUKIDASHI'))
        o.write('/* 0 is a dot at each end, 1 an arrow */\n')
        o.write('#define JW_SUN_ARROW       %d\n' % d('Arrow'))
        o.write('#define JW_SUN_ARROW_LEN   %g\n' % f('ArrowLength'))
        o.write('#define JW_SUN_ARROW_ANG   %g\n' % f('ArrowAngle'))
        o.write('#define JW_SUN_ARROW_SOLID %d\n' % d('ArrowSolid'))
        o.write('/* how the number is written */\n')
        o.write('#define JW_SUN_DECIMALS    %d\n' % d('SHOUSUUKETA'))
        o.write('#define JW_SUN_COMMA       %d\n' % d('ShowComma'))
        o.write('#define JW_SUN_ZERO        %d\n' % d('ShowZero'))
        o.write('#define JW_SUN_UNIT        %d\n' % d('ShowUnit'))
        o.write('\n/* The flags the original puts on each part (+0x44).  Read\n'
                '   back out of a dimension it drew. */\n')
        o.write('#define JW_SUN_LINE_FLAGS  0x2000u\n')
        o.write('#define JW_SUN_TEN_FLAGS   0x0040u\n')
        o.write('#define JW_SUN_TEXT_FLAGS  0x4010u\n')
        o.write('/* and the word at +0x2c a dimension value carries, which an ordinary\n'
                '   text has as 0 */\n')
        o.write('#define JW_SUN_TEXT_WIDTH  0x2043u\n')
        o.write('\n#endif\n')
    print('wrote', OUT)


main()
