#!/usr/bin/env python3
"""Generate src/gen/sunpodlg.h -- the 寸法設定 dialog (32925's).

The same way as tools/mkzokusel.py: tools/jwdraw.ps1's `dlg:` step sends the
command once a range is in, walks the dialog's children with
EnumChildWindows and writes down each control's class, id, style, text and
rectangle in the dialog's own client coordinates (decomp/res/sunpodlg.txt).
It also paints the dialog into a PNG, which is docs/ref_sunpodlg.png.

A tall one: the numbers a dimension is drawn with, a couple of combos and
a great many checkboxes.  Nothing of it is wired up yet -- this is the
picture only.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkmoji import esc                            # noqa: E402

SRC = 'decomp/res/sunpodlg.txt'
OUT = 'src/gen/sunpodlg.h'
MASK = 'docs/sunpodlg_textareas.txt'

WS_VISIBLE = 0x10000000
BORDER = 8
CAPTION = 31
W, H, CW, CH = 384, 590, 368, 551
TITLE = '寸法設定'


def kind_of(cid, cls, style):
    if cls == 'Button':
        low = style & 0xf
        if low == 3:                    # BS_AUTOCHECKBOX
            return 'CHECK'
        if low == 9:                    # BS_AUTORADIOBUTTON
            return 'RADIO'
        if low == 7:                    # BS_GROUPBOX
            return 'GROUP'
        return 'OK' if cid in (1, 2) else 'PUSH'
    if cls == 'Edit':
        # 1001 is the one inside a combo box, which is drawn with it
        return None if cid == 1001 else 'EDIT'
    if cls == 'ComboBox':
        return 'COMBO'
    if cls == 'Static':
        return 'STATIC'
    return None


def main():
    rows = []
    for line in io.open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line or line.startswith('==='):
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if not (int(style, 16) & WS_VISIBLE):
            continue
        k = kind_of(int(cid), cls, int(style, 16))
        if k is None:
            continue
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, int(chk),
                     (int(style, 16) & 0xf) == 1, int(en), text))

    if not os.path.isdir('src/gen'):
        os.makedirs('src/gen')
    f = io.open(OUT, 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mksunpodlg.py from decomp/res/sunpodlg.txt\n'
            '   -- read out of the running original, see that script */\n')
    f.write('#ifndef JW_GEN_SUNPODLG_H\n#define JW_GEN_SUNPODLG_H\n\n')
    f.write('#define JW_SD_W   %d\n' % W)
    f.write('#define JW_SD_H   %d\n' % H)
    f.write('#define JW_SD_CW  %d\n' % CW)
    f.write('#define JW_SD_CH  %d\n' % CH)
    f.write('#define JW_SD_BORDER %d\n' % BORDER)
    f.write('#define JW_SD_CAPTION %d\n' % CAPTION)
    f.write('#define JW_SD_TITLE "%s"\n\n' % esc(TITLE))
    f.write('enum { JW_SD_OK, JW_SD_CHECK, JW_SD_PUSH, JW_SD_STATIC,\n'
            '       JW_SD_COMBO, JW_SD_GROUP, JW_SD_EDIT, JW_SD_RADIO };\n\n')
    f.write('typedef struct {\n'
            '    short x, y, w, h;      /* the dialog\'s client area */\n'
            '    short id;\n'
            '    unsigned char kind;\n'
            '    unsigned char on;\n'
            '    unsigned char deflt;   /* BS_DEFPUSHBUTTON: an extra dark\n'
            '                              border round it */\n'
            '    unsigned char enabled;\n'
            '    const char *text;      /* CP932 */\n'
            '} jw_sd_t;\n\n')
    f.write('static const jw_sd_t jw_sunpodlg[] = {\n')
    for x, y, ww, hh, cid, k, chk, dft, en, text in rows:
        f.write('    { %4d, %4d, %4d, %3d, %5d, JW_SD_%-6s, %d, %d, %d,'
                ' "%s" },\n'
                % (x, y, ww, hh, cid, k, chk, dft, en, esc(text)))
    f.write('};\n#define JW_NSUNPODLG %d\n\n' % len(rows))
    f.write('#endif\n')
    f.close()

    g = io.open(MASK, 'w', encoding='utf-8', newline='\n')
    g.write('# Where the 寸法設定 dialog draws text with a Windows font, in\n'
            '# the coordinates of docs/ref_sunpodlg.png (the whole %dx%d\n'
            '# window).  The frame and the caption go with them.  Written by\n'
            '# tools/mksunpodlg.py.\n\n' % (W, H))
    g.write('0 0 %d %d\n' % (W, CAPTION))
    g.write('0 %d %d %d\n' % (CAPTION, BORDER, CH))
    g.write('%d %d %d %d\n' % (W - BORDER, CAPTION, BORDER, CH))
    g.write('0 %d %d %d\n' % (H - BORDER, W, BORDER))
    for x, y, ww, hh, cid, k, chk, dft, en, text in rows:
        x += BORDER
        y += CAPTION
        if k in ('CHECK', 'RADIO'):
            g.write('%d %d %d %d\n' % (x + 14, y - 1, ww - 13, hh + 2))
        elif k in ('STATIC', 'COMBO', 'EDIT'):
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, hh + 2))
        elif k == 'GROUP':
            # only the strip its label sits in, which is also where the top
            # of its frame runs
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, 17))
        else:
            g.write('%d %d %d %d\n' % (x + 3, y + 3, ww - 6, hh - 6))
    g.close()
    print('%s: %d controls, %s' % (OUT, len(rows), MASK))
    return 0


if __name__ == '__main__':
    sys.exit(main())
