"""decomp/res/widepen.txt -> src/gen/wide.h.

What tools/gdiwide.c measured: for a pen `w` pixels wide, the pixels GDI
covers for a line along an axis, as a start and end delta for each offset
across the line.  The port walks a line pixel by pixel, so it uses the table
the other way round: for each offset across the line, walk the line from
`start` steps before its first pixel to `end` steps after its last.

Width 1 is in there too (0, -1: LineTo leaves its last point out), so one
piece of code covers every pen.
"""
import io, os, sys

SRC = 'decomp/res/widepen.txt'
OUT = 'src/gen/wide.h'
WMAX = 16

tab = {}
for line in io.open(SRC, encoding='ascii'):
    if line.startswith('#'):
        continue
    w, ax, d, a, b = line.split()
    tab[(int(w), ax, int(d))] = (int(a), int(b))

out = io.StringIO()
out.write('/* generated by tools/mkwide.py from decomp/res/widepen.txt --\n'
          '   what GDI covers with a wide pen, see tools/gdiwide.c */\n'
          '#ifndef JW_GEN_WIDE_H\n#define JW_GEN_WIDE_H\n\n'
          '#define JW_WIDE_MAX %d\n\n'
          '/* [width - 1][offset + width / 2] = { start, end }, in steps\n'
          '   along the line.  _H is for a line that runs mostly across,\n'
          '   _V for one that runs mostly up or down. */\n' % WMAX)
for ax, name in (('h', 'JW_WIDE_H'), ('v', 'JW_WIDE_V')):
    out.write('static const signed char %s[JW_WIDE_MAX][JW_WIDE_MAX][2] = {\n'
              % name)
    for w in range(1, WMAX + 1):
        row = []
        for i in range(WMAX):
            d = i - w // 2
            row.append(tab.get((w, ax, d), (0, 0)) if i < w else (0, 0))
        out.write('    { /* %2d */ ' % w
                  + ', '.join('{%2d,%2d}' % p for p in row) + ' },\n')
    out.write('};\n\n')
out.write('#endif\n')

text = out.getvalue()
if os.path.exists(OUT) and io.open(OUT, encoding='ascii').read() == text:
    sys.exit(0)
io.open(OUT, 'w', encoding='ascii', newline='\n').write(text)
