#!/usr/bin/env python3
"""Generate src/gen/zokuhen.h -- the 属性変更 dialog (範囲選択's 1070).

The same way as tools/mkzoku.py and tools/mkmoji.py: the dialog is read out
of the running original rather than worked out from its template.
tools/jwdraw.ps1's `dlg:b` step presses the button once a box has been
taken, walks the dialog's children with EnumChildWindows and writes down
each control's class, id, style, text and rectangle in the dialog's own
client coordinates (decomp/res/zokuhen.txt).  It also paints the dialog into
a PNG, which is docs/ref_zokuhen.png.

**This is the other half of the 属性選択 dialog.**  The template carries
both sets of controls -- 《...指定》 to pick elements out by what they are
and 《...に変更》 to change them -- and 属性変更 shows the second.  Twenty-
six of the forty-seven children have no WS_VISIBLE here, and those are the
ones left out.

Nothing here comes out of the picture: the checkbox is the same flat 3-D one
the command bars and the 線属性 dialog draw (src/ui.c's paint_checkbox), and
everything else is a box, a line or a piece of text.  docs/ref_zokuhen.png
is kept all the same, as what tests/zokuhen2_test.c scores the port's own
picture against.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkmoji import esc                            # noqa: E402

SRC = 'decomp/res/zokuhen.txt'
OUT = 'src/gen/zokuhen.h'
MASK = 'docs/zokuhen_textareas.txt'

WS_VISIBLE = 0x10000000
BORDER = 8
CAPTION = 31


def kind_of(cid, cls, style):
    if cls == 'Button':
        low = style & 0xf
        if low == 3:                    # BS_AUTOCHECKBOX
            return 'CHECK'
        return 'OK' if cid in (1, 2) else 'PUSH'
    if cls == 'Static':
        return 'STATIC'
    return None


def main():
    rows = []
    for line in io.open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line or line.startswith('==='):
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if not (int(style, 16) & WS_VISIBLE):
            continue                    # the 属性変更 half
        k = kind_of(int(cid), cls, int(style, 16))
        if k is None:
            continue
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, int(chk),
                     int(en), text))

    if not os.path.isdir('src/gen'):
        os.makedirs('src/gen')
    f = io.open(OUT, 'w', encoding='ascii', newline='\n')
    f.write('/* generated by tools/mkzokuhen.py from decomp/res/zokuhen.txt\n'
            '   and docs/ref_zokuhen.png -- read out of the running original,\n'
            '   see that script */\n')
    f.write('#ifndef JW_GEN_ZOKUHEN_H\n#define JW_GEN_ZOKUHEN_H\n\n')
    f.write('/* the dialog itself, in the frame\'s client area */\n')
    f.write('#define JW_ZH_W   287\n')
    f.write('#define JW_ZH_H   476\n')
    f.write('#define JW_ZH_CW  271\n')
    f.write('#define JW_ZH_CH  437\n')
    f.write('#define JW_ZH_BORDER %d\n' % BORDER)
    f.write('#define JW_ZH_CAPTION %d\n\n' % CAPTION)
    f.write('enum { JW_ZH_OK, JW_ZH_CHECK, JW_ZH_PUSH, JW_ZH_STATIC };\n\n')
    f.write('typedef struct {\n'
            '    short x, y, w, h;      /* the dialog\'s client area */\n'
            '    short id;\n'
            '    unsigned char kind;\n'
            '    unsigned char on;      /* what the original had it at */\n'
            '    unsigned char enabled;\n'
            '    const char *text;      /* CP932 */\n'
            '} jw_zh_t;\n\n')
    f.write('static const jw_zh_t jw_zokuhen[] = {\n')
    for x, y, ww, hh, cid, k, chk, en, text in rows:
        f.write('    { %4d, %4d, %4d, %3d, %5d, JW_ZH_%-6s, %d, %d,'
                ' "%s" },\n'
                % (x, y, ww, hh, cid, k, chk, en, esc(text)))
    f.write('};\n#define JW_NZOKUHEN %d\n\n' % len(rows))
    f.write('#endif\n')
    f.close()

    # and where the original draws text with a Windows font, which the port
    # cannot match glyph for glyph -- the same list the other two dialogs
    # have, worked out from the controls rather than by hand
    g = io.open(MASK, 'w', encoding='utf-8', newline='\n')
    g.write('# Where the 属性選択 dialog draws text with a Windows font, in\n'
            '# the coordinates of docs/ref_zokuhen.png (the whole %dx%d\n'
            '# window).  The frame and the caption go with them: Windows\n'
            '# draws those itself.  Written by tools/mkzokuhen.py.\n#\n'
            '#   python tools/cmp.py docs/ref_zokuhen.png '
            'tests/out/zokuhen.png -i %s\n\n' % (287, 476, MASK))
    g.write('0 0 287 %d\n' % CAPTION)                   # the caption
    g.write('0 %d %d 437\n' % (CAPTION, BORDER))        # the left edge
    g.write('%d %d %d 437\n' % (287 - BORDER, CAPTION, BORDER))
    g.write('0 %d 287 %d\n' % (476 - BORDER, BORDER))   # and the bottom
    for x, y, ww, hh, cid, k, chk, en, text in rows:
        x += BORDER
        y += CAPTION
        if k == 'CHECK':                # after the box, which the port draws
            g.write('%d %d %d %d\n' % (x + 14, y - 1, ww - 13, hh + 2))
        elif k == 'STATIC':
            g.write('%d %d %d %d\n' % (x - 1, y - 1, ww + 2, hh + 2))
        elif k == 'PUSH':
            # inside its two edge rows.  One more than the OK buttons get:
            # 基点変更 is greyed out and the original draws its words a
            # pixel higher than the port does.
            g.write('%d %d %d %d\n' % (x + 2, y + 2, ww - 4, hh - 4))
        else:                           # OK, inside its own edges
            g.write('%d %d %d %d\n' % (x + 3, y + 3, ww - 6, hh - 6))
    g.close()
    print('%s: %d controls, %s' % (OUT, len(rows), MASK))
    return 0


if __name__ == '__main__':
    sys.exit(main())
