#!/usr/bin/env python3
"""Generate src/gen/zoku.h -- the 線属性 dialog (0x8027).

Like the command bars, the dialog is read out of the running original rather
than worked out from its template: tmp/jwdraw.ps1's `dlg:` step sends the
command, walks the dialog's children with EnumChildWindows and writes down
each control's class, id, style, text and rectangle in the dialog's own
client coordinates (decomp/res/zoku.txt).  It also paints the dialog into a
PNG, which is what docs/ref_zoku.png is and what tests/zoku_test.c scores
the port against.

Only the controls that are actually on the screen are kept: the dialog
carries a second, hidden set of labels for the SXF line types, and a couple
of hidden boxes for the line width, none of which are visible unless SXF
extended colours are turned on.
"""
import os
import re

SRC = 'decomp/res/zoku.txt'
OUT = 'src/gen/zoku.h'

WS_VISIBLE = 0x10000000


def esc(s):
    BS = chr(92)
    keep = '"' + BS + '?'
    out = []
    b = s.encode('cp932')
    for i, c in enumerate(b):
        if c > 0x7e or c < 0x20 or chr(c) in keep:
            out.append(BS + 'x%02x' % c)
            if i + 1 < len(b) and chr(b[i + 1]) in '0123456789abcdefABCDEF':
                out.append('" "')
        else:
            out.append(chr(c))
    return ''.join(out)


def kind_of(cid, cls):
    if 1401 <= cid <= 1409:
        return 'COLOR', cid - 1400
    if 2449 <= cid <= 2457:
        return 'TYPE', cid - 2448
    if cid == 1:
        return 'OK', 0
    if cid == 2:
        return 'CANCEL', 0
    if cid == 2312:
        return 'CHECK', 0
    if cls == 'Static':
        return 'STATIC', 0
    return None, 0


def main():
    rows = []
    for line in open(SRC, encoding='utf-8'):
        line = line.rstrip('\n')
        if '|' not in line:
            continue
        cls, cid, x, y, w, h, style, chk, en, text = line.split('|', 9)
        if not (int(style, 16) & WS_VISIBLE):
            continue                    # the SXF set, and the width boxes
        k, n = kind_of(int(cid), cls)
        if k is None:
            continue
        rows.append((int(x), int(y), int(w), int(h), int(cid), k, n, text))
    os.makedirs('src/gen', exist_ok=True)
    with open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('/* generated by tools/mkzoku.py from decomp/res/zoku.txt --\n'
                '   read out of the running original, see that script */\n')
        f.write('#ifndef JW_GEN_ZOKU_H\n#define JW_GEN_ZOKU_H\n\n')
        f.write('/* the dialog itself, in the frame\'s client area: the\n'
                '   original centres it across and in the client above the\n'
                '   status bar, which came to 478,162 in a 1264x741 one */\n')
        f.write('#define JW_ZOKU_W   308\n')
        f.write('#define JW_ZOKU_H   375\n')
        f.write('#define JW_ZOKU_CW  292\n')
        f.write('#define JW_ZOKU_CH  336\n')
        f.write('#define JW_ZOKU_BORDER 8\n')
        f.write('#define JW_ZOKU_CAPTION 31\n\n')
        f.write('enum { JW_ZK_COLOR, JW_ZK_TYPE, JW_ZK_OK, JW_ZK_CANCEL,\n'
                '       JW_ZK_CHECK, JW_ZK_STATIC };\n\n')
        f.write('typedef struct {\n'
                '    short x, y, w, h;      /* the dialog\'s client area */\n'
                '    short id;\n'
                '    unsigned char kind;\n'
                '    unsigned char n;       /* which colour or line type */\n'
                '    const char *text;      /* CP932 */\n'
                '} jw_zk_t;\n\n')
        f.write('static const jw_zk_t jw_zoku[] = {\n')
        for x, y, w, h, cid, k, n, text in rows:
            f.write('    { %4d, %4d, %4d, %3d, %5d, JW_ZK_%-6s, %d, "%s" },\n'
                    % (x, y, w, h, cid, k, n, esc(text)))
        f.write('};\n#define JW_NZOKU %d\n\n' % len(rows))
        f.write('#endif\n')
    print('%s: %d controls' % (OUT, len(rows)))


if __name__ == '__main__':
    main()
